### ISSUE TITLE
 ValueError: invalid filename or file not found

### ISSUE THREAD

**Issue by Nazari-Fariba** [atomistic-machine-learning/schnetpack#106]
Hi all,
I have installed schentpack on windows .
python version is 3.7.3
when i run pytest it returns the following error:
 ValueError: invalid filename or file not found "c:\users\fariba\appdata\local\programs\python\python37\lib\site-packages\schnetpack-0.2.1-py3.7.egg\schnetpack\sacred\calculator_ingredients.py"
Any comment is appreciated.

**Comment by Stefaanhess** [comment]
Hi @Nazari-Fariba,

the installation command from the ReadMe.md had problems with installing some packages.
Try to uninstall schnetpack with 'pip uninstall schnetpack' and reinstall it with 'pip install .' instead of 'python setup.py install'.
#107
