### ISSUE TITLE
No activation function in last dense layer in filter generator

### ISSUE THREAD

**Issue by Dom1L** [atomistic-machine-learning/schnetpack#131]
Hey!

I have a question regarding the filter generator network. In your code you don't use the SSP activation after the last dense layer in the filter generator, whereas in all publication figures there seems to be one. 

https://github.com/atomistic-machine-learning/schnetpack/blob/cdecaed2489f6c8bde99a846805428e4f4a3f5a7/src/schnetpack/representation/schnet.py#L40

Was this on purpose?
It's probably really minor, but I was curious.

Thanks!

**Comment by ktschuett** [comment]
Yes, this is on purpose, so now the filter can have negative values. However, in practice it does not make much of a difference.

**Comment by Dom1L** [comment]
Thanks for the clarification!
