### ISSUE TITLE
qm9_*.py in example folder not work...

### ISSUE THREAD

**Issue by liuxiaotong15** [atomistic-machine-learning/schnetpack#141]
python qm9_tutorial.py 
INFO:root:get dataset
INFO:schnetpack.data.atoms:Starting download
INFO:root:Downloading GDB-9 data...
INFO:root:Done.
INFO:root:Extracting files...
INFO:root:Done.
INFO:root:Parse xyz files...
INFO:root:Parsed:  10000 / 133885
INFO:root:Parsed:  20000 / 133885
INFO:root:Parsed:  30000 / 133885
INFO:root:Parsed:  40000 / 133885
INFO:root:Parsed:  50000 / 133885
INFO:root:Parsed:  60000 / 133885
INFO:root:Parsed:  70000 / 133885
INFO:root:Parsed:  80000 / 133885
INFO:root:Parsed:  90000 / 133885
INFO:root:Parsed: 100000 / 133885
INFO:root:Parsed: 110000 / 133885
INFO:root:Parsed: 120000 / 133885
INFO:root:Parsed: 130000 / 133885
INFO:root:Write atoms to db...
INFO:root:Done.
INFO:root:Downloading GDB-9 atom references...
INFO:root:Done.
INFO:schnetpack.data.loader:statistics will be calculated...
INFO:root:build model
Traceback (most recent call last):
  File "qm9_tutorial.py", line 38, in <module>
    spk.Atomwise(
AttributeError: module 'schnetpack' has no attribute 'Atomwise'

and 

python qm9_schnet.py 
Traceback (most recent call last):
  File "qm9_schnet.py", line 20, in <module>
    output = schnetpack.atomistic.Atomwise()
TypeError: __init__() missing 1 required positional argument: 'n_in'

help help, I use the latest code pulled from github and python3.7, it seems the schnetpack version I use is wrong?

**Comment by Stefaanhess** [comment]
#143 should fix the issue
