### ISSUE TITLE
readme should be updated?

### ISSUE THREAD

**Issue by liuxiaotong15** [atomistic-machine-learning/schnetpack#142]
there is no schnetpack_qm9.py in folder. so is the readme outdated?

**Comment by liuxiaotong15** [comment]
I found when I run docs/tutorials/02_qm9.ipynb, md_tutorials branch can work well but master can not.

**Comment by bartolsthoorn** [comment]
Yes you are right, an updated README is in this PR: https://github.com/atomistic-machine-learning/schnetpack/pull/140

**Comment by bartolsthoorn** [comment]
Try running:
```
spk_run.py train <schnet/wacsf> qm9 <datadir> <modeldir>
```
It should download the QM9 data automatically.

**Comment by ktschuett** [comment]
Thx! Merged PR #140
