### ISSUE TITLE
sorry, but master branch still not work...

### ISSUE THREAD

**Issue by liuxiaotong15** [atomistic-machine-learning/schnetpack#144]
python spk_run.py train schnet qm9 qm9_data qm9_model --split 1000 200
Traceback (most recent call last):
  File "spk_run.py", line 5, in <module>
    from schnetpack.utils.script_utils import settings
ImportError: cannot import name 'settings' from 'schnetpack.utils.script_utils'

**Comment by Stefaanhess** [comment]
Hey @liuxiaotong15 ,
 your dbpath should link to a database. Not to the folder.
Can you try to run:

python spk_run.py train schnet qm9 qm9_data/qm9.db qm9_model --split 1000 200

Does this solve the problem?

**Comment by liuxiaotong15** [comment]
no, same error
I think it will download auto, but no... even i copy a db file in that folder... still same error

**Comment by liuxiaotong15** [comment]
Python 3.7.4 (default, Aug  2 2019, 11:35:29) 
[GCC 5.4.0 20160609] on linux

**Comment by bartolsthoorn** [comment]
Could you make sure you have installed with `pip install .` and then run `spk_run.py ...` from another directory (note WITHOUT `python` before, because pip installs `spk_run.py` as an executable).

**Comment by liuxiaotong15** [comment]
yes, you figure out the problem... @bartolsthoorn thank you so much...
I use "find" command and run in script folder... 
and maybe i know what is the problem, the first line in the script folder is #!/usr/bin/env python. that path is  a python2 in my computer. After install the first line change to /home/lxt/code/py37_env/py37_env/bin/python3.7
