### ISSUE TITLE
Evaluation on validation split fails

### ISSUE THREAD

**Issue by bartolsthoorn** [atomistic-machine-learning/schnetpack#149]
The following command produces an empty evaluation.txt:
```
spk_run.py eval modeldir --split validation
```

The reason is that the split name in code is expected to be "val". However, the util parsing script only allows the full word, i.e. validation. So I think the code where "val" is still used should be changed to "validation" as well.

**Comment by Stefaanhess** [comment]
Thanks, I fixed it.
