### ISSUE TITLE
Possible incorrect variable used in schnetpack_matproj.py

### ISSUE THREAD

**Issue by lauri-codes** [atomistic-machine-learning/schnetpack#15]
The following part in "schnetpack_matproj.py" near line 257:
```python
    split_path = os.path.join(args.modelpath, 'split.npz')
    if args.mode == 'train':
        if args.split_path is not None:
            copyfile(args.split_path, split_path)

    data_train, data_val, data_test = mp.create_splits(*train_args.split, split_file=split_path)
```
seems to create problems when the split is being specified as two integers in train_args.split instead of a split file in args.split_path. The mp.create_splits()-function will ignore the train_args.split parameters as the split_path-variable will always be a valid string. One way to correct the behaviour could be with:
```python
    split_path = None
    if args.mode == 'train':
        if args.split_path is not None:
            split_path = os.path.join(args.modelpath, 'split.npz')
            copyfile(args.split_path, split_path)

    data_train, data_val, data_test = mp.create_splits(*train_args.split, split_file=split_path)
```

**Comment by ktschuett** [comment]
As far as I see, this should not cause any problems: `mp.create_splits()` does only use the supplied `split_path` if it exists, otherwise it writes the indices of the created split into a new file.

However, this might not be the most transparent way to do this...

**Comment by lauri-codes** [comment]
Yes you're right, on the first run there is no problem. However, after running the script once, a "splits.npz" file is created automatically. Then if the script is run for a second time in the same folder, the parameters given in the train_args.split are ignored, and the file "splits.npz" is used although it was not specified in args.split_path. This happens only though if you run the script multiple times with different split arguments and use the same "modeldir".

**Comment by pankessel** [comment]
I am not sure if I follow. The file "splits.npz" contains all indices of the randomly generated split. By no means does it only contain two integers. We need to store these indices before training is finished such that training can be restarted.

**Comment by lauri-codes** [comment]
Ok, I see. I would then simply overwrite the existing file, and ensure that if the model folder has a "splits.npz" file, it is not loaded by default if not specified in args.split_path.

**Comment by pankessel** [comment]
Thanks for your reply. I am hesitant to implement this because it could lead to the user accidentally overwriting the spilt files. I would therefore prefer to print a warning if both arguments are specified and the split file already exists. Would that be a solution for you as well? Thanks again for your detailed feedback. This is much appreciated.

**Comment by lauri-codes** [comment]
Yes, a warning might be even better. That solution would be just fine for me, as long as the split file is not loaded, if not given as argument in args.split_path. Thanks for the quick response!
