### ISSUE TITLE
Slow Training

### ISSUE THREAD

**Issue by jwz-ecust** [atomistic-machine-learning/schnetpack#155]
Hi,
I am appreciated for the NN framework. I have used SchNet in my dataset (clusters, 20-100 atoms). I found the training process is too slow (training: 100,000, almost three days' training) and the most time is spent on data loader. Is there any methods to accelerate the data loader? I have tried the [prefetcher](https://github.com/NVIDIA/apex/issues/304) but there is no obvious promotion. 

Configuration list
- platform: ubuntu 16.04
- gtx 1080ti
- i5 8400

Here is the [prefetcher code](https://github.com/jwz-ecust/schnetpack/blob/dev/src/schnetpack/datasets/cluster.py)

Thanks!

Jiawei Zhang

**Comment by ktschuett** [comment]
Did you try to increase the number of workers?
```
loader = AtomsLoader(dataset, num_workers=XXX)
```

Otherwise, if you get an accurate network after three days, it does not sound too bad....

**Comment by ktschuett** [comment]
Also, if you didn't, you should try the `schnetpack.environment.TorchEnviromentProvider`:
```
dataset = AtomsData(..., environment_provider=TorchEnvironmentProvider(cutoff=5.))
```
