### ISSUE TITLE
what is the meaning of cell and cell_offset in one batch?

### ISSUE THREAD

**Issue by wmmxk** [atomistic-machine-learning/schnetpack#156]
This is not exactly an issue. I had a hard time to understand the meaning of "cell" and "cell_offset" in a batch generated by a data loader. I did not find out how the two properties were generated. Could you explain or point me to the code if there is any?

**Comment by ktschuett** [comment]
Both properties are related to periodic boundary conditions. The `cell` contains the lattice vectors, while `cell_offset` are integer offsets set characterize the unit cell in which a neighbor is located.

E.g. given a unit cell `L \in R^{3x3}`, the center atom at position rA and the neighboring atom is at position rB in a neighboring cell with offset O=[2, 3, 4], the distance between both atoms is:
```
d_{AB} = || r_A - ( r_B +  L O^T) ||
```

**Comment by ktschuett** [comment]
Would be a nice addition to the docs.

**Comment by wmmxk** [comment]
Thanks for your reply. It seems not complicated. 

But I am still not sure how to calculate "cell" and "cell_offset" when applying schnet on another dataset. Do you know what is the input for calculating these two values given a molecule?

**Comment by wmmxk** [comment]
Could you explain what "lattice vectors" in your reply? How are "lattice vectors" related to the "[atomic_numbers and positions](https://github.com/atomistic-machine-learning/schnetpack/blob/bd8af39a014c99ec347ac26ccf8b3f747b29917a/src/schnetpack/representation/schnet.py#L206)" of a molecule?

**Comment by wmmxk** [comment]
I just found there is a function named "collect_neighbors" for generating the offset in another[ repo](https://github.com/atomistic-machine-learning/SchNet/blob/49a1e6031f50d79a83ea21148b8e8cbcabdaabb7/src/schnet/atoms.py#L30). And [cell=at.cell.](https://github.com/atomistic-machine-learning/SchNet/blob/f5254f9a4b869eb3e61fa3efc5ff10da3b1f4c63/src/schnet/atoms.py#L42). Is the "cell" and "offset" in that repo is the same as the "cell" and "cell_offset" in this repo?.  (I think it is, but just want confirmation).

**Comment by wmmxk** [comment]
I looked into the definition of [Atoms class](https://github.com/rosswhitfield/ase/blob/6bb4f84f898e6b5262fff94444f6e9980875c1ef/ase/atoms.py#L208). It seems the "cell" is always a (3,3) numpy array of zeros for the QM9 dataset. 
For the "offset", it is also a zero numy array because it is a [product](https://github.com/atomistic-machine-learning/SchNet/blob/f5254f9a4b869eb3e61fa3efc5ff10da3b1f4c63/src/schnet/atoms.py#L56) of an array and "cell". The shape of "offset" is (n, n-1, 3), where n is the number of atoms in a molecule. 
If I am wrong, I will glad to be corrected.

**Comment by ktschuett** [comment]
> Could you explain what "lattice vectors" in your reply? How are "lattice vectors" related to the "[atomic_numbers and positions](https://github.com/atomistic-machine-learning/schnetpack/blob/bd8af39a014c99ec347ac26ccf8b3f747b29917a/src/schnetpack/representation/schnet.py#L206)" of a molecule?

It is for periodic boundary conditions in materials. If you have a single molecule, you can ignore it. The pbc in your ase.Atoms should be set set to `False` and everything is ok.


> I just found there is a function named ["collect_neighbors"](https://github.com/atomistic-machine-learning/SchNet/blob/49a1e6031f50d79a83ea21148b8e8cbcabdaabb7/src/schnet/atoms.py#L30). for generating the offset in an older repo. And [cell=at.cell.](https://github.com/atomistic-machine-learning/SchNet/blob/f5254f9a4b869eb3e61fa3efc5ff10da3b1f4c63/src/schnet/atoms.py#L42). Is the "cell" and "offset" in that repo is the same as the "cell" and "cell_offset" in this repo?. (I think it is, but just want confirmation).

Yes, that is essentially the same as in schnetpack [https://github.com/atomistic-machine-learning/schnetpack/blob/master/src/schnetpack/nn/neighbors.py](https://github.com/atomistic-machine-learning/schnetpack/blob/master/src/schnetpack/nn/neighbors.py)
