### ISSUE TITLE
unit of dipole moment in orca_parser.py

### ISSUE THREAD

**Issue by tangzeyuan** [atomistic-machine-learning/schnetpack#177]
Hi all,

I notice that orca_parser.py only read "Total Dipole Moment" from orca.log file (e.g. [test_orca.log#957](https://github.com/atomistic-machine-learning/schnetpack/blob/37b3b13021e291f3e1c94e23653b191d03132b3d/tests/data/test_orca.log#L957)), but "Magnitude (a.u.)" or "Magnitude (Debye)" is ignored. 

In [orca_parser.py#L638](https://github.com/atomistic-machine-learning/schnetpack/blob/37b3b13021e291f3e1c94e23653b191d03132b3d/src/schnetpack/md/parsers/orca_parser.py#L638), should we read dipole_moment_unit (e.g. Debye) from orca.log file first and then change it to `Properties.dipole_moment: OrcaFormatter(4, stop=7, unit=dipole_moment_unit)`?

Best,
Zeyuan

**Comment by mgastegger** [comment]
By default, the total dipole moment vector is read, which is given in atomic units. The magnitude is simply the length of this vector. The use of atomic units is intended, as it makes handling a lot of different properties significantly easier in the long run.
However, if you should require Debye you can either specify the conversion factor in the OrcaFormatter as suggested above (should be around 2.54) or add a simple postprocessing step.

**Comment by tangzeyuan** [comment]
@mgastegger Thanks for your clarification. I'm just not sure how schnetpack reads the unit of dipole moment.
