### ISSUE TITLE
merge two MD17 dataset

### ISSUE THREAD

**Issue by neojie** [atomistic-machine-learning/schnetpack#204]
I was trying to merge two MD17 datasets (dat1.db, dat2.db). They have the same shape of cell, same atoms, but different configurations. I want to merge them to form a new dataset. Is there any easy way of doing it? The way I can think about is to 
`    db_md17 = AtomsData('new.db', available_properties=['energy','forces'])
`
then iterate over dat1.db and dat2.db add add the atoms and properties into the new.db by
`
db_md17.add_systems(atoms, property_list)
`
But I do not think this is the best way given that we already have dat1.db and dat2.db in MD17 format.

**Comment by mgastegger** [comment]
Unfortunately, there is no such simple way to merge datasets yet.

One way like you described would be to load both datasets, then iterate over the second to collect atoms and properties and add them to the first dataset via `add_system`/`add_systems`. One would have to convert to numpy arrays inbetween.

**Comment by neojie** [comment]
OK. Thank you.
