### ISSUE TITLE
Units Conversion 

### ISSUE THREAD

**Issue by L3viAckerman** [atomistic-machine-learning/schnetpack#219]
Hi,
I am reproducing the paper results and when I read the code, I see the units of the QM9 mu using in code is Angstrom, not is Debye. I am confusing a bit about this. The results that get when run the code in properties QM9 mu, the results I get must convert to Debye to get the paper results. So, the MAE loss must multiply by 4.803204673 ( Angstrom to Debye). And the MAE is 0.033 in the paper is equal with the loss MAE 0.00687 that get when run code. Am I wrong something? Please help me!
Thank you so much!

**Comment by mgastegger** [comment]
Hi, you are right, the dipole moment in QM9 is converted from Debye to ASE internal units. And to convert the loss back to Debye you need to multiply by 4.803204673. This means the MAE reported corresponds to a MAE of 0.00687 output by the default scripts, as you said.

**Comment by L3viAckerman** [comment]
Thank you so much!
