### ISSUE TITLE
Something seems worng with the split.npz

### ISSUE THREAD

**Issue by L3viAckerman** [atomistic-machine-learning/schnetpack#220]
Dear,
I am reproducing the results in the QM9 dataset. I found the  trained benchmark-models in the document. But when I saw closer, I found that the split.npz file of the qm9 dipole moment does not match with the dataset. In the args.json, I see the ***remove_uncharacterized*** param is true so the total molecules in QM9 is 130831. But the total index in the ***split.npz*** file is 133885. So I think the split file is not match with the setting of model. Could you check it again.
Thank you so much!
Best wishes!

**Comment by Stefaanhess** [comment]
Hey @L3viAckerman ,
I will close this issue and move the discussion to #222 .
