### ISSUE TITLE
MD simulation with environment set

### ISSUE THREAD

**Issue by neojie** [atomistic-machine-learning/schnetpack#225]
Hi,
I was using the MD module and wondering if there is anyway that the environment info (for example AseEnvironmentProvider(5)) can be included when load the starting structure.
I trained my model  by
```
data = AtomsData(db, environment_provider=AseEnvironmentProvider(5))
...
schnet = spk.representation.SchNet(
    n_atom_basis=n_features,
    n_filters=n_features,
    n_gaussians=25,
    n_interactions=3,
    cutoff=5.,
    cutoff_network=spk.nn.cutoff.CosineCutoff
)
```
I used the best model to do the MD simulation. If I just use  `md_system.load_molecules_from_xyz(molecule_path)`, the environment info cannot be included and  predicted energy and forces are off. Any way to include the  environment info?
Thank you!

**Comment by neojie** [comment]
Alright, I think I may have (partly?) solved the problem by modifying the `_generate_input` function under `schnet_calculator.py`. Here is the modification I made

```
    def _generate_input(self, system):
        """
        Function to extracts neighbor lists, atom_types, positions e.t.c. from the system and generate a properly
        formatted input for the schnetpack model.

        Args:
            system (schnetpack.md.System): System object containing current state of the simulation.

        Returns:
            dict(torch.Tensor): Schnetpack inputs in dictionary format.
        """

        positions, atom_types, atom_masks = self._get_system_molecules(system)
        cell      = system.cell.astype(np.float32)
        atoms = ase.Atoms(numbers = atom_types[0].detach().numpy(),
                  positions = positions[0].detach().numpy(),
                  cell = cell,pbc=True)
        environment_provider            = AseEnvironmentProvider(5) # I manually put the environment here
        neighbor_list_org, offset_org = environment_provider.get_environment(atoms)
        neighbor_list_org                     =  neighbor_list_org.astype(int)
        
        nbh    = torch.tensor(neighbor_list_org)[None,:]
        offset = torch.tensor(offset_org)[None,:]
        mask = nbh >= 0
        neighbor_mask = mask.long()
        neighbors = (nbh * mask.long())

        inputs = {
            Properties.R: positions,
            Properties.Z: atom_types,
            Properties.atom_mask: atom_masks, # not change
            Properties.cell: torch.tensor(cell)[None,:],
            Properties.cell_offset: offset,
            Properties.neighbors: neighbors,
            Properties.neighbor_mask: neighbor_mask,
        }

        return inputs
```
The output force and potential are close to what they should be. Does this modification make sense to you?
Thank you!

**Comment by mgastegger** [comment]
This looks reasonable. Basically the only thing the above wrapper adds is an additional buffer zone and a check how far the atoms moved so that the neighbor list does only have to be recomputed if the atoms move too far.

The only thing to look out for are the units, the MD system uses atomic units (Bohr etc) internally. This needs to be consistent with the cutoff, if no conversion happens when you get the atoms from the system.

**Comment by neojie** [comment]
I see. Thank you. One more question is that when the starting molecule structure is loaded using the `System` class, it seems that the cell information is not loaded. I wonder if the cell size info is discarded in the MD simulation.  Also, is the periodic boundary condition is taken care in the MD simulation?  I tried reading the source code but could find the implementation of periodic boundary condition in MD simulation modules.

**Comment by mgastegger** [comment]
Unfortunately, these are all parts missing from the current master. All these things (+barostats, wrapping etc.) are present in the `pbc_update` branch (hence the name). Since there are other updates to come, we did not integrate into the master yet. It should work without problems for models trained in the master branch, as basic SchNet was not touched. This might be worth giving a try in your case.

**Comment by neojie** [comment]
Thank you. `pbc_update` branch is very helpful.
