### ISSUE TITLE
Efficiency tuning

### ISSUE THREAD

**Issue by coolcodecamper** [atomistic-machine-learning/schnetpack#228]
Dear developers,

I like SchNetPack a lot.
It seems the code can be made more efficient.
For example pytorch recommends to use torch.nn.parallel.DistributedDataParallel(model) instead of torch.nn.DataParallel(model).
Here I found some simple guidelines, e.g. to avoid transfers between cpu and gpu:
https://towardsdatascience.com/7-tips-for-squeezing-maximum-performance-from-pytorch-ca4a40951259 

I would be happy to see this great package developed further!

**Comment by Stefaanhess** [comment]
Hey @coolcodecamper ,
thanks for your remark! I will have a look at it.

**Comment by ktschuett** [comment]
We're going to move to lightning soon, so this will be solved then.
