### ISSUE TITLE
Training Problem with structures with constraint

### ISSUE THREAD

**Issue by jwz360** [atomistic-machine-learning/schnetpack#229]
I tried to train schnet on structures with energy and forces, in which some atoms are fixed. I found that the losses were infinite. My understanding is that fixed atoms' forces are zero but relaxed atoms are not, which may result in performing very sick matrix calculations. Any idea to solve it? 
Thanks!

**Comment by mgastegger** [comment]
In general, also the forces on relaxes atoms should be zero.

**Comment by jwz360** [comment]
@mgastegger Thanks for your advice. Finally, I found the reason. Actually, it caused by ase's read module. For old version, It would treat constrained atoms position as zero. I upgrade ase to the up-to-date one, it fixed.

**Comment by mgastegger** [comment]
Multiple atoms with the same positions do indeed sound problematic. Great to hear that you found the issue.
