### ISSUE TITLE
Warnings with latest version of PyTorch

### ISSUE THREAD

**Issue by Dankomaister** [atomistic-machine-learning/schnetpack#230]
Hi!

Running schnetpack gives a lot of repeated warnings during training.
The two repeated errors I get are the following:
`python3.8/site-packages/schnetpack/data/atoms.py:330: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629395347/work/torch/csrc/utils/tensor_numpy.cpp:141.)
  properties[pname] = torch.FloatTensor(row.data[pname])`
I guess this happens because the numpy arrays in the db have the read only flag set.

The second error is this one:
`python3.8/site-packages/schnetpack/environment.py:290: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629395347/work/torch/csrc/utils/python_arg_parser.cpp:766.)
  in_cutoff = (distances < cutoff).nonzero()`
This is related to the TorchEnvironmentProvider it seems.

/Daniel

**Comment by Dankomaister** [comment]
Should just mention that this occurs with PyTorch version 1.6.0

**Comment by Stefaanhess** [comment]
Hey @Dankomaister ,
sorry for the late reply. I will try to find out what is going on there

**Comment by Stefaanhess** [comment]
#233 should remove the warnings. Thanks @Dankomaister

**Comment by Dankomaister** [comment]
Great I'm getting no warnings now, thanks!

**Comment by Stefaanhess** [comment]
nice :)
