### ISSUE TITLE
ASE interface SpkCalculator cache results

### ISSUE THREAD

**Issue by coolcodecamper** [atomistic-machine-learning/schnetpack#232]
Dear developers,

the ASE Calculator class stores results in cache (energy, forces, ...).
If there are multiple calls to the calculate function but no system_changes (positions, ...) have occured, results can be obtained instantly from cache.
I believe it requires only one additional line ("if self.calculation_required(atoms, properties):") in the SpkCalculator class in schnetpack/interfaces/ase_interface.py to make use of the cache. The line should be inserted in the calculate function below the first call of the original calculator ("Calculator.calculate(self, atoms)"). The remaining part of the function should be indented, so it is only executed if the additional line returns True.

**Comment by mgastegger** [comment]
Thank you for the info, this should indeed be simple to fix. I will have a look.

**Comment by mgastegger** [comment]
I added the caching of the ASE results.
