### ISSUE TITLE
QM9 dataset best model

### ISSUE THREAD

**Issue by kobebranyt** [atomistic-machine-learning/schnetpack#241]
Do you have some best models for QM9 dataset which have been trained already for using?

**Comment by Stefaanhess** [comment]
Hey @kobebranyt ,
we have some trained models for QM9 here: https://schnetpack.readthedocs.io/en/stable/getstarted/benchmarks.html
They have been trained on the QM9 dataset, without removing the uncharacterized molecules.

**Comment by kobebranyt** [comment]
Thank you!
when I use the model learning from QM9 to predict some other molecules' energy, I meet "AttributeError: 'AtomisticModel' object has no attribute 'requires_stress'", how to solve this problem?

**Comment by kobebranyt** [comment]
Thank you!
when I use the model learning from QM9 to predict some other molecules' energy, I meet "AttributeError: 'AtomisticModel' object has no attribute 'requires_stress'", how to solve this problem?

**Comment by Stefaanhess** [comment]
The pretrained models have been trained with an older spk version. If you use `spk.utils.load_model()` instead of `torch.load()`, the model will automatically be updated to the latest version.

**Comment by kobebranyt** [comment]
Thank you!
