### ISSUE TITLE
QM9 training

### ISSUE THREAD

**Issue by 6-Qingying** [atomistic-machine-learning/schnetpack#242]
Hello,
I have trained a model using 50k traing examples, and I want to continue to train a new model using 120k training examples based on the original model. I copy the files (log.csv, best_model, checkpoints) in optput folder, changed 'num_train=50000' to 'num_train=120000' and went on with my training. However, after several training steps, it stopped and the output follows: ValueError: could not convert string to float: 'Time'' .  Have I done something wrong? >-<
Thanks for help!

**Comment by Stefaanhess** [comment]
Hey @6-Qingying ,
are you using the `spk_run.py` script for training? Could you maybe add the full error message, so I can see where the error occurs?

**Comment by 6-Qingying** [comment]
I'm traing using the script written by myself.

The output (if any) follows:
/opt/conda/conda-bld/pytorch_1591914880026/work/torch/csrc/utils/tensor_numpy.cpp:141: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable te    nsors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before     converting it to a tensor. This type of warning will be suppressed for the rest of this program.
/share/home/qywu/miniconda3/lib/python3.7/site-packages/ase/atoms.py:921: VisibleDeprecationWarning: Use get_global_number_of_atoms() instead
   np.VisibleDeprecationWarning)
  Traceback (most recent call last):
   File "learn2.py", line 79, in <module>
     skiprows=-8, delimiter=',')
   File "/share/home/qywu/miniconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1159, in loadtxt
     for x in read_data(_loadtxt_chunksize):
  File "/share/home/qywu/miniconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1087, in read_data
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/share/home/qywu/miniconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1087, in <listcomp>
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/share/home/qywu/miniconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 794, in floatconv
    return float(x)
 ValueError: could not convert string to float: 'Time'

**Comment by Stefaanhess** [comment]
This seems to be related to the `loadtxt`-function. What file are you trying to load in line 79?

**Comment by 6-Qingying** [comment]
log.csv  
`results = np.loadtxt(os.path.join(args.log, 'log.csv'), skiprows=-8, delimiter=',')`

**Comment by Stefaanhess** [comment]
The problem here is, that you are loading the header (which starts with 'Time') and then `loadtxt` is trying to cast it to float. This fix should work:

`results = np.loadtxt(os.path.join(args.log, 'log.csv'), skiprows=1, delimiter=',')[:-8]`

**Comment by 6-Qingying** [comment]
It works! Thank you so much! ^_^

**Comment by Stefaanhess** [comment]
Nice :)
