### ISSUE TITLE
Not able to reduce MAE on OMDB

### ISSUE THREAD

**Issue by MiracAydin1** [atomistic-machine-learning/schnetpack#249]
Dear All,

First of all, thanks for creating an awesome tool like SchNetPack. 

I created a model following the documentation of SchNetPack and ran it for bandgap prediction using QM9 database for my molecule. The molecule contains 161 atoms.

First I created db from xyz file of the molecule (xyz file just includes atom numbers and coordinates) and fed into the model but it performed very bad with QM9. I think QM9 does not contains big molecules like this. Then I moved to OMDB to test the molecule according to the following article:

1. Band gap prediction for large organic crystal structures with machine learning

The article says that MAE is around 0.4 when SchNetPack is used with OMDB-GAP1 database. I applied the values of parameters that has been mentioned in the article but  I never reached this value with both databases. After that, I changed paramaters according to trained models of SchNetPack on the website: [benchmarks of SchNetPack](https://schnetpack.readthedocs.io/en/stable/getstarted/benchmarks.html) 

I trained 2 identical models according to article above and trained SchNet bandgap model (In the original paper of Schnet, bandgap MAE is around 0.07). Cutoff is the only difference between models. Here is the results:

**Model-1**
MAE: 0.81
Prediction: 3.25 eV
Truth: 3.50 eV
cutoff: 4A

**Model-2**
MAE: 0.55
Prediction: 0.96 eV
Truth: 3.50 eV
cutoff: 10A

The following code has been used to train models above:

`import os`
`import schnetpack as spk`
`from schnetpack.datasets import OrganicMaterialsDatabase as OMDB`

`omdbase = './omdbase'`
`if not os.path.exists('omdbase'):`
`os.makedirs(omdbase)`

`omdata = OMDB('/home/eduline/Desktop/schnetpack/databases/OMDB-GAP1_v1.1.tar.gz')`

`train, val, test = spk.train_test_split(`
`data=omdata,`
`num_train=9000,`
`num_val=1000,`
`split_file=os.path.join(omdbase, "split.npz"),`
`)`

`batchsize = 32`
`n_epochs = 500`
`lr_rate = 1e-4`

`train_loader = spk.AtomsLoader(train, batch_size=batchsize, shuffle=True)`
`val_loader = spk.AtomsLoader(val, batch_size=batchsize)`

`schnet = spk.representation.SchNet(`
`n_atom_basis=128, n_filters=128, n_gaussians=50, n_interactions=3,`
`cutoff=4., cutoff_network=spk.nn.cutoff.CosineCutoff`
`)`

`output_gap = spk.atomistic.Atomwise(n_in=128, atomref=atomrefs[OMDB.BandGap], property=OMDB.BandGap,`
`mean=means[OMDB.BandGap], stddev=stddevs[OMDB.BandGap])`

`model = spk.AtomisticModel(representation=schnet, output_modules=output_gap)`

`from torch.optim import Adam`

`optimizer = Adam(model.parameters(), lr=lr_rate)`

`os.system("rm -r ./omdbase/checkpoints")`
`os.system("rm -r ./omdbase/log.csv")`

`import schnetpack.train as trn`
`loss = trn.build_mse_loss([OMDB.BandGap])`
`metrics = [spk.metrics.MeanAbsoluteError(OMDB.BandGap)]`
`hooks = [`
`trn.CSVHook(log_path=omdbase, metrics=metrics),`
`trn.ReduceLROnPlateauHook(`
`optimizer,`
`patience=5, factor=0.8, min_lr=1e-6,`
`stop_after_min=True`
`)`
`]`
`trainer = trn.Trainer(`
`model_path=omdbase,`
`model=model,`
`hooks=hooks,`
`loss_fn=loss,`
`optimizer=optimizer,`
`train_loader=train_loader,`
`validation_loader=val_loader,`
`)`

`device = "cuda" # change to 'cpu' if gpu is not available`
`trainer.train(device=device, n_epochs=n_epochs)`

As a results, I barely succeeded to reduce MAE by changing cutoff  but Model-2 is far away to predict bandgap of the molecule. I am stucked in this problem.

If you can help i would appreciate.

Best regards,
Miraç Aydın

**Comment by Stefaanhess** [comment]
Hey @MiracAydin1 ,
sorry for not replying to this issue! Did you make any progress on this, or do you still need help?
Stefaan

**Comment by MiracAydin1** [comment]
Hello @Stefaanhess ,

Thank you for reply. I progressed a little bit in this topic.

But I have a problem about running my model on multiple GPU. I could not find anything about this in Schnetpack documents and article. So I tried torch.nn.DataParallel as it follows:

```
import torch
import torch.nn as nn

model = spk.AtomisticModel(representation=schnet, output_modules=output_gap)
model = nn.DataParallel(model)
```

But I encountered the following error:

`RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)``

If you have any suggestion about running on multiple GPU, it would be very great.

Best regards,
Miraç

**Comment by Stefaanhess** [comment]
Hi @MiracAydin1 ,

maybe this is an issue with the torch/cuda installation? I found this on the pytorch-discussion forum: https://discuss.pytorch.org/t/cuda-error-cublas-status-internal-error-when-calling-cublascreate-handle/114341

Does the error also occur when you run this?

    import torch.nn as nn
    
    model = nn.Linear(10, 10)
    model = nn.DataParallel(model)

Best regards,
Stefaan

**Comment by MiracAydin1** [comment]
Hello @Stefaanhess,

Thank you for your reply. Let me give a code snippet of my model first:

```
schnet = spk.representation.SchNet(
    n_atom_basis=128, n_filters=128, n_gaussians=50, n_interactions=6,
    cutoff=5., cutoff_network=spk.nn.cutoff.CosineCutoff
    )

output_gap = spk.atomistic.Atomwise(n_in=128, atomref=atomrefs[OMDB.BandGap], property=OMDB.BandGap,
                                    mean=means[OMDB.BandGap], stddev=stddevs[OMDB.BandGap])

import torch
import torch.nn as nn

#model = spk.AtomisticModel(representation=schnet, output_modules=output_gap)
model = nn.Linear(10, 10)
model = nn.DataParallel(model)

from torch.optim import Adam

# loss function
def mse_loss(batch, result):
    diff = batch[OMDB.BandGap]-result[OMDB.BandGap]
    err_sq = torch.mean(diff ** 2)
    return err_sq

# build optimizer
optimizer = Adam(model.parameters(), lr=lr_rate)

os.system("rm -r ./omdbase/checkpoints")
os.system("rm -r ./omdbase/log.csv")

import schnetpack.train as trn
loss = trn.build_mse_loss([OMDB.BandGap])
metrics = [spk.metrics.MeanAbsoluteError(OMDB.BandGap)]
hooks = [
        trn.CSVHook(log_path=omdbase, metrics=metrics),
        trn.ReduceLROnPlateauHook(
        optimizer,
        patience=25, factor=0.8, min_lr=1e-6,
        stop_after_min=True
        )
    ]
trainer = trn.Trainer(
        model_path=omdbase,
        model=model,
        hooks=hooks,
        loss_fn=loss,
        optimizer=optimizer,
        train_loader=train_loader,
        validation_loader=val_loader,
        )
 
```
The code part above is the main section of the model.
When I tried "nn.Linear(10,10)" instead of "model = spk.AtomisticModel(representation=schnet, output_modules=output_gap)" it gives the following error:

```
TypeError: Caught TypeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/kuacc/users/exc-maydin/.conda/envs/schnet/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/kuacc/users/exc-maydin/.conda/envs/schnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/kuacc/users/exc-maydin/.conda/envs/schnet/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "/kuacc/users/exc-maydin/.conda/envs/schnet/lib/python3.6/site-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
TypeError: linear(): argument 'input' (position 1) must be Tensor, not dict
```

In the Schnetpack article, it says that the model can be ran on multiple GPU. Do you have any suggestion how I can run my model on multiple GPU or how did you run on multiple GPU or split your test models? Because I could not succeed it so far and my model does not fit into single GPU. It consumes almost 31GB GPU RAM (I had a chance to run my model on Tesla V100 and saw this amount of RAM when the model was running). I can send the entire model via email or add a Google Drive link here if you want to take a look.

I appreciate your help. Thank you.

Best regards,
Miraç

**Comment by Stefaanhess** [comment]
Hey @MiracAydin1 ,
it should be possible to train the model on multiple GPUs. Therefore you would only need to use the `nn.DataParallel` module (like you already did). On my GPUs this works fine, so I am not sure what is happening with your GPUs. Could you maybe also add the full Traceback of the `RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling cublasCreate(handle)` -error?
I only wanted you to test the `nn.Linear` so I could see if simple modules work on multiple GPU on your system, or if it only causes trubble with our model. Of course the linear layer can not handle the spk-inputs, since it expects tensors. You would need to run something like

    import torch
    import torch.nn as nn

    model = nn.Linear(10, 10)
    model = nn.DataParallel(model).to("cuda")
    model(torch.rand(5, 10).to("cuda"))

in order to check if it runs well.
In case you want to already want to run your training while we figure out what is going on with the parallel training you could try to reduce the batchsize, in order to run it on the single V100. We use a batchsize of 32 for pbc data. I think this should fit on the V100. I also noticed that you should set `aggregation_mode="avg"` in the output layer, and `divide_by_n_atoms=False` in the statistics calculation. Otherwise your model will not train very well. From my experience I would also suggest to use a smaller lr_patience (e.g. 15), otherwise your training will take very long :)

Best regards,
Stefaan

**Comment by MiracAydin1** [comment]
Hi @Stefaanhess,

Thank you for your advices.

I tried your sample code but it gave the same error. Probably system configuration (CUDA and pyTorch versions etc.) and architecture confliction cause this problem. But i have not figured it out yet. We can say that the error is not caused by Schnetpack.

Lastly, could you please write your PyTorch, Python and CUDA version on your system which is currently running fine? Maybe I can try that version to maintain consistency.

After writing your versions, we can close the ticket.

Best regards,
Miraç

**Comment by Stefaanhess** [comment]
Hey @MiracAydin1 ,

I am using the following versions:
python 3.8
pytorch 1.7.1
cuda 10.2

Did you check this issue on pytorch discuss (https://discuss.pytorch.org/t/cuda-error-cublas-status-internal-error-when-calling-cublascreate-handle/114341)? Someone has the same error message as you do and they seem to fix it by fixing the versions/installation.

Best regards and good luck,
Stefaan
