### ISSUE TITLE
How could I run on multiple CPUs?

### ISSUE THREAD

**Issue by norlandn** [atomistic-machine-learning/schnetpack#273]
Hello, I just tested this code and run the qm9 dataset training on two computers only with CPU. However, it used one CPU core on one computer and 6 core on another. And I checked the docs and issues here and don't find how to set up the CPU cores. Could someone tell me how I can do it? Thanks!

**Comment by Stefaanhess** [comment]
Hey @norlandn ,

there is no implementation for distributed CPU training in schnetpack. If you want to specify a single cpu you could use `x.to("cpu:0")` and for Multiple CPUs you could checkout the `DistributedDataParallel` -module from pytorch. They had a `DistributedDataParallelCPU` in earlier versions (e.g. 1.0) but it is missing in the recent torch versions.

Best,
Stefaan

**Comment by norlandn** [comment]
Thank you! I'll try that.
