### ISSUE TITLE
SpkCalculator produce repeating decimal digits

### ISSUE THREAD

**Issue by otayfuroglu** [atomistic-machine-learning/schnetpack#276]
Hi everybody,

When I run MD calculation with the Spkcalculator  (from ase interface) using my model,   potential energy values produced have repeating decimal digits (e.g. .375, .500, .250, .875, .750). Is it normal to produce any other than these numbers? Or is there a problem with my model or calculator?

Output follow:
Time[ps]      Etot[eV]        Epot[eV]              Ekin[eV]    T[K]
0.0000     -2012735.707 -2012742.375        6.668    99.2
0.0005     -2012736.190 -2012751.500       15.310   227.8
0.0010     -2012736.983 -2012771.500       34.517   513.5
0.0015     -2012737.352 -2012791.250       53.898   801.9
0.0020     -2012737.720 -2012804.750       67.030   997.2
0.0025     -2012738.572 -2012810.750       72.178  1073.8
0.0030     -2012738.591 -2012810.875       72.284  1075.4
0.0035     -2012739.145 -2012808.250       69.105  1028.1
0.0040     -2012740.005 -2012804.750       64.745   963.2
0.0045     -2012740.307 -2012802.250       61.943   921.6
.
.
.

thanks in advance

**Comment by ktschuett** [comment]
Perhaps this is an issue with float32 precision on the GPU. You could try subtracting the the single atom energies and/or mean energy before fitting the model and adding it back in the calculator after converting back to float64.

**Comment by otayfuroglu** [comment]
Thanks a lot for answer @ktschuett. I tried your advice then my model produced reasonable decimal digits.This was a very quick solution. thank you very much.

Bests,
