### ISSUE TITLE
MD17 benchmark

### ISSUE THREAD

**Issue by sakuraiiiii** [atomistic-machine-learning/schnetpack#286]
Hi, it is a very nice work. However, I have some questions w.r.t the results on MD17 dataset, which I didn't find in the papers. First, what's the cutoff radius for this dataset? Second, the benchmark of energy is the MAE per molecule or the MAE per atom? And that of forces is the MAE per molecule or MAE per atom, or MAE per atom per component? If the results are MAE per molecule, when the library is used for supercell of a crystal, maybe the MAE will be very large, since the number of atoms is very large. These make me confused. Thank you very much.

**Comment by ktschuett** [comment]
Sorry for the late response.

1. In the original paper there was not cutoff. But you can set it to 5 A which works well.
2. MAE per molecule
3. MAE / atom / component (i.e. mean over all force components)

For periodic structures, you should use energy / atom and also average over the atomwise energy contributions (set ``--aggregation_mode avg`` when calling spk_run).
