### ISSUE TITLE
qm9 dataset has no attribute "properties"

### ISSUE THREAD

**Issue by peder2tm** [atomistic-machine-learning/schnetpack#29]
qm9 dataset has an attribute called "available_properties", but I think it should be "properties" to be consistent with the rest. The "schnetpack_qm9.py" script also refers to "properties" which currently doesn't exist.

**Comment by ktschuett** [comment]
Thanks! It should be `avaiblable_properties` in all datasets, in order to distinguish it from the `properties` in the init which determines, which properties should be loaded.

@Stefaanhess Could you fix this?

**Comment by Stefaanhess** [comment]
#32

**Comment by ktschuett** [comment]
@Stefaanhess Was this fixed by merging #32?

**Comment by Stefaanhess** [comment]
Yes, I renamed the property attributes for all datasets to 'properties'.
