### ISSUE TITLE
Does trained schnet potential be able to use in LAMMPS?

### ISSUE THREAD

**Issue by Roy-Kid** [atomistic-machine-learning/schnetpack#307]
Hi, I want to use Schnetpack to fit a polymer potential, and embed to the lammps then do simulation. So is there any way to export the trained potential/Neural network to use in the LAMMPS, like what deepmd do?

**Comment by ktschuett** [comment]
I wanted to look into this, also for OpenMM. It seems that you need to write some interface code in C++. Do you have any experience with this?

**Comment by Roy-Kid** [comment]
I have a little experiment to extend LAMMPS and write a book which I think is the best tutorial for now. You can find it at the official website of LAMMPS [ ](https://lammps.org/books.html) and can download ebook from [ ](http://libgen.rs/search.php?req=LAMMPS&open=0&res=25&view=simple&phrase=1&column=def).

And I am learning how to write OpenMM plugin because We are developing an auto differentiate multipole forcefield. We can exchange the experiment more often.

**Comment by mgastegger** [comment]
We added a LAMMPS interface in PR #501. Documentation can be found in the [How-To](https://schnetpack.readthedocs.io/en/latest/howtos/lammps.html) section of the docs.
