### ISSUE TITLE
How to add Pressure in 'simulation.hdf5' file?

### ISSUE THREAD

**Issue by siddharth-ncl-work** [atomistic-machine-learning/schnetpack#321]
Is there any hook to add pressure in 'simulation.hdf5' for monitoring purpose.
I am aware that there is a tensorboard hook but that makes analysis difficult as pressure needs to be extracted from event files. 

I am able to get stress tensor in 'simulation.hdf5', is there any way to calculate pressure from stress tensor?

**Comment by mgastegger** [comment]
Sorry for the late reply. The full pressure can be computed from the stress tensor as:
<a href="https://www.codecogs.com/eqnedit.php?latex=p&space;=&space;\frac{2&space;E_\mathrm{kin}}{3V}&space;-&space;\frac{1}{3}\mathrm{Tr}[\sigma]" target="_blank"><img src="https://latex.codecogs.com/svg.latex?p&space;=&space;\frac{2&space;E_\mathrm{kin}}{3V}&space;-&space;\frac{1}{3}\mathrm{Tr}[\sigma]" title="p = \frac{2 E_\mathrm{kin}}{3V} - \frac{1}{3}\mathrm{Tr}[\sigma]" /></a>
The first term depends on the kinetic energy and the volume of the cell, which can be extracted from the hdf5 file (e.g. with `HDF5Loader.get_kinetic_energy()`) and computed from the cell.
The second term is the average of the diagonal terms in the stress tensor.

We are currently working on a new iteration of the package, where these things will be much easier to access.

**Comment by siddharth-ncl-work** [comment]
@mgastegger , thanks a lot for getting back to me, I really appreciate taking time to help me out.

I have two questions:
1. What units are length/volume and pressure values reported in hdf5 and evenfiles?
2. I tried calculating the pressure through hdf5 file using the formula as well as from tensorboard eventfile, unfortunately they are not matching.

![download](https://user-images.githubusercontent.com/43916742/132023990-41245586-6ff6-4b5d-bef1-f4a061361778.png)

[hdf5_and_eventfile.zip](https://github.com/atomistic-machine-learning/schnetpack/files/7106739/hdf5_and_eventfile.zip)

**Comment by mgastegger** [comment]
The length volume/values in the hdf5 file use nanometers. The pressure in the event file is reported in bar.
The stress tensor is currently logged in model units, which probably is the reason for the difference.

If I use kcal/mol/A^3 for the stress tensor, I get something better resembling the event file pressure.
```
from schnetpack.md import HDF5Loader
from schnetpack.md import MDUnits

data = HDF5Loader("simulation.hdf5")

ekin = data.get_kinetic_energy()
stress = data.get_property("stress")
cell = data.get_property("_cell")

vol = np.linalg.det(cell)
stress_iso = 1./3. * np.einsum("bii->b", stress)

# Convert to internal units assuming stress is kcal/mol/A^3
stress_iso = stress_iso * MDUnits.unit2internal("kcal/mol/A/A/A")

# Compute pressure
p = 2./3. * ekin / vol - stress_iso

# Convert to bar
p = p / MDUnits.bar2internal
```
![image](https://user-images.githubusercontent.com/36198330/132028363-bf9bc3b0-384b-4ac6-ace8-6a009d33db1b.png)

**Comment by siddharth-ncl-work** [comment]
I did use "kcal/mol/A^3" for the stress tensor in my model. After converting pressure to internal units plots are matching quite well at my end. Again, thanks a lot for the help.

![download (2)](https://user-images.githubusercontent.com/43916742/132033988-93049d96-2d68-493c-b482-660ca3b38e96.png)
