### ISSUE TITLE
Is PaiNN available in schnetpack?

### ISSUE THREAD

**Issue by jstoppelman** [atomistic-machine-learning/schnetpack#323]
Hello, I saw the talk about PaiNN at ACS last week, and was interested in testing it out on my systems to see if we see improvement for some properties compared to SchNet. Will PaiNN be included as part of the next update to SchNetPack?

**Comment by ktschuett** [comment]
Yes, it is already in the dev branch. You can already give it a try, there are some major changes compared to master that are not fully documented yet.
