### ISSUE TITLE
Preparing our own data  for  PyTroch Lightning Trainer 

### ISSUE THREAD

**Issue by Manyi-Yang** [atomistic-machine-learning/schnetpack#327]
Hi, I  would like to know how to train a model with multi GPU.  If the master version of the code supports it?  if yes, How should  I set up my calculation?  
In issue #253 it mentioned that the version using Pytorch lightning can run MD with multi GPU. 
How should I prepare our own data for the PyTorch Lightning Trainer?  Thanks

**Comment by Stefaanhess** [comment]
Hey @Manyi-Yang 
you can just add `--parallel` to the run arguments. This enables the use of miltiple GPUs. In the current version we do not use the pytorch-lightning trainer yet. This will change in the next major update of schnetpack, which is about to be finished

**Comment by Manyi-Yang** [comment]
Thank you very much. 
I also have another question about the Unit:
When we prepare the custom dataset, which kind of unit should we use.  EV  eV/A  or Kcal/mol Kcal/mol/A for energy and force?  Also, what are the units for the coordinate and PBC cells? 
Does this unit is consistent with the output log.csv file?  
Thanks again.

**Comment by Stefaanhess** [comment]
For the properties (energy, forces, ...) you can select the units by yourself. The model does not care about these units and the log file will also be in the units that have been used for training. For the coordinates and the cell properties you should use Ang.

**Comment by Manyi-Yang** [comment]
Thank you very much!
