### ISSUE TITLE
eval problem

### ISSUE THREAD

**Issue by gravity-lhg** [atomistic-machine-learning/schnetpack#330]
I have trained the model, ready to test the performance of the model. 
using "spk_run.py eval ../model/ --split test --cuda" got a issue :  spk_run.py eval: error: the following arguments are required: modelpath
I don’t know how this model path is set, and does it need to enter the model file name and type？

**Comment by gravity-lhg** [comment]
well, You missed the <datapath> at "To evaluate the trained model with the best validation error"

**Comment by Stefaanhess** [comment]
> well, You missed the datapath at "To evaluate the trained model with the best validation error"

Yes, the datapath was missing. `spk_run.py eval datapath modelpath --split test` should do it. Is that missing in the tutorials?

**Comment by Stefaanhess** [comment]
Ok I found and fixed it
