### ISSUE TITLE
Latest commit causes 2 failed tests during installation regarding cuda

### ISSUE THREAD

**Issue by harpaf13** [atomistic-machine-learning/schnetpack#337]
I installed the latest version of schnetpack today and after running pytest had the following 2 errors

```
==================== short test summary info =====================
FAILED tests/test_scripts_utils.py::test_get_loaders[small_batch]
FAILED tests/test_scripts_utils.py::test_get_loaders[big_batch]
========= 2 failed, 158 passed, 23094 warnings in 40.33s =========
```

When i rolled back the version to commit `5dd3d3f` and re-installed, all tests were passed. The full output errors are shown in pytest-output.txt
[pytest-output.txt](https://github.com/atomistic-machine-learning/schnetpack/files/7196055/pytest-output.txt)

**Comment by Stefaanhess** [comment]
Hey @harpaf13 ,
sorry for the late reply and thanks for the info. It seems like I forgot to update a test function...
I am not sure why Travis even allowed me to commit, but I will check that.
