### ISSUE TITLE
No inheritance of ASEEnvironmentProvider

### ISSUE THREAD

**Issue by Sangwon91** [atomistic-machine-learning/schnetpack#34]
https://github.com/atomistic-machine-learning/schnetpack/blob/9caa03c5ca27ab17f02201c4146487c8917521f3/src/schnetpack/environment.py#L55

There are no functional issues, but I think `ASEEnvironmentProvider` should inherit `BaseEnvironmentProvider` like below.

```python
class ASEEnvironmentProvider(BaseEnvironmentProvider):
```

And in my opinion, the name of the class should be changed to `AseEnvironmentProvider` because in the other module (e.g., `md`) the word `Ase` is used for ASE related classes (e.g., `md.AseInterface`).  The naming conventions should be used consistently.

**Comment by ktschuett** [comment]
Yes, sounds reasonable. I'll have a look.
