### ISSUE TITLE
Will the next version of SchNetPack include SpookyNet?

### ISSUE THREAD

**Issue by Sangwon91** [atomistic-machine-learning/schnetpack#340]
I wonder if you have any plans to implement spookynet on the schnetpack interface.
It would be great if I could use spookynet with the elegant interface of schnetpack.

Thank you.

**Comment by ktschuett** [comment]
Not at first, but we aim to include it at some point.

**Comment by NiklasGebauer** [comment]
Due to time constraints, we did not implement SpookyNet for our SchNetPack 2.0 release and do not plan to do so in the near future. We will close this issue for now but if there is more demand, please feel free to re-open it.
