### ISSUE TITLE
Error in tutorial 4 code section 32 and some minor issue

### ISSUE THREAD

**Issue by wuziqi-cmu** [atomistic-machine-learning/schnetpack#343]
When running tutorial 4, I encountered several problems:

1. the tests/data path is wrong
2. fs2atu attribute not found
3. In code section 32, the error message is shown below:
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/var/folders/k_/jq6m6ps14v59j7zn4tqygzjr0000gn/T/ipykernel_43873/4039029887.py in <module>
      1 n_steps = 50000
      2 
----> 3 rpmd_simulator.simulate(n_steps)

~/opt/anaconda3/envs/SchNet/lib/python3.9/site-packages/schnetpack/md/simulator.py in simulate(self, n_steps)
     76         # Perform initial computation of forces
     77         if self.system.forces is None:
---> 78             self.calculator.calculate(self.system)
     79 
     80         # Call hooks at the simulation start

~/opt/anaconda3/envs/SchNet/lib/python3.9/site-packages/schnetpack/md/calculators/schnet_calculator.py in calculate(self, system)
     91 
     92         inputs = self._generate_input(system)
---> 93         self.results = self.model(inputs)
     94         self._update_system(system)
     95 

~/opt/anaconda3/envs/SchNet/lib/python3.9/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1049         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1050                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1051             return forward_call(*input, **kwargs)
   1052         # Do not call functions when jit is used
   1053         full_backward_hooks, non_full_backward_hooks = [], []

~/opt/anaconda3/envs/SchNet/lib/python3.9/site-packages/schnetpack/atomistic/model.py in forward(self, inputs)
     63             )
     64 
---> 65         inputs["representation"] = self.representation(inputs)
     66         outs = {}
     67         for output_model in self.output_modules:

~/opt/anaconda3/envs/SchNet/lib/python3.9/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1049         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1050                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1051             return forward_call(*input, **kwargs)
   1052         # Do not call functions when jit is used
   1053         full_backward_hooks, non_full_backward_hooks = [], []

~/opt/anaconda3/envs/SchNet/lib/python3.9/site-packages/schnetpack/representation/schnet.py in forward(self, inputs)
    225 
    226         # compute interatomic distance of every atom to its neighbors
--> 227         r_ij = self.distances(
    228             positions, neighbors, cell, cell_offset, neighbor_mask=neighbor_mask
    229         )

~/opt/anaconda3/envs/SchNet/lib/python3.9/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1049         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1050                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1051             return forward_call(*input, **kwargs)
   1052         # Do not call functions when jit is used
   1053         full_backward_hooks, non_full_backward_hooks = [], []

~/opt/anaconda3/envs/SchNet/lib/python3.9/site-packages/schnetpack/nn/neighbors.py in forward(self, positions, neighbors, cell, cell_offsets, neighbor_mask)
    117 
    118         """
--> 119         return atom_distances(
    120             positions,
    121             neighbors,

~/opt/anaconda3/envs/SchNet/lib/python3.9/site-packages/schnetpack/nn/neighbors.py in atom_distances(positions, neighbors, cell, cell_offsets, return_vecs, normalize_vecs, neighbor_mask)
     70         # -> distances[mask==0] = 0.0
     71         tmp_distances = torch.zeros_like(distances)
---> 72         tmp_distances[neighbor_mask != 0] = distances[neighbor_mask != 0]
     73         distances = tmp_distances
     74 

IndexError: The shape of the mask [1, 9, 8] at index 0 does not match the shape of the indexed tensor [4, 9, 8] at index 0

Any help on how to resolve those bugs? Thanks a lot!

**Comment by mgastegger** [comment]
Hi, I was not able to reproduce the path issue, but could fix the other problems.
`fs2atu` no longer exists, since we changed the internal unit system and the third issue was due to the neighbor list not properly adapting to the changed number of replicas. The updated tutorial/code is now in the master branch and should work again properly.
