### ISSUE TITLE
Bug in Train Embeddings for Elemental References?

### ISSUE THREAD

**Issue by WardLT** [atomistic-machine-learning/schnetpack#35]
I think the train_embeddings value of `Atomwise` is used incorrectly. When setting the default references in the constructor for `Atomwise`, the value of `freeze` for the embeddings class is equal to `train_embeddings` which means that if `train_embeddings == True` then the embeddings are not trained.

Do I understand that correctly? And, if so, could I fix it by changing it to `freeze=not train_embeddings`?

One of the two relevant lines:

https://github.com/atomistic-machine-learning/schnetpack/blob/9caa03c5ca27ab17f02201c4146487c8917521f3/src/schnetpack/atomistic.py#L141

**Comment by ktschuett** [comment]
Oh, you're right, this should be the other way around. Fortunately, it does not really have an impact on performance.

**Comment by ktschuett** [comment]
Fixed by #37
