### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'features'

### ISSUE THREAD

**Issue by loilisxka** [atomistic-machine-learning/schnetpack#362]
when running spk_run.py with custom datasets to train wASCF, I get the following error
 I am running python 3.7.0 and my pip version is 21.2.2 
fe.db file is created by spk_parse.py
![QQ图片20211102092846](https://user-images.githubusercontent.com/43001784/139773106-e5c7b166-1403-4c33-bcf9-d42e22be4a05.png)
![QQ图片20211102093410](https://user-images.githubusercontent.com/43001784/139773125-b4f7d614-273c-4d54-8962-8b245b3a19bb.png)

**Comment by Stefaanhess** [comment]
Hey @loilisxka ,
I think the problem in this case is the wrong output module. By default the script uses the `Atomwise` output module, which is designed for SchNet. Could you rerun the script and add `--output_module elemental_atomwise` to your rung arguments? Let me know if this helps.

**Comment by loilisxka** [comment]
thanks for your reply，
According to your suggestion, the network can start training normally, but a new problem has occurred.



Perhaps this is because the size of the data has not changed?&nbsp;
Please tell me a solution, or can you give me a script? Just like you teach people how to use SchNet to training a model on forces and energies in the Schnetpack document


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "atomistic-machine-learning/schnetpack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月2日(星期二) 下午4:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [atomistic-machine-learning/schnetpack] AttributeError: 'Namespace' object has no attribute 'features' (Issue #362)





 
Hey @loilisxka ,
 I think the problem in this case is the wrong output module. By default the script uses the Atomwise output module, which is designed for SchNet. Could you rerun the script and add --output_module elemental_atomwise to your rung arguments? Let me know if this helps.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Stefaanhess** [comment]
I think the training should basically be the same as with SchNet.
What is the new error, that you are getting?

**Comment by loilisxka** [comment]
oh Sorry,&nbsp;the picture may not be sent. The screenshot of the new question is attached to the email this time




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "atomistic-machine-learning/schnetpack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月2日(星期二) 下午5:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [atomistic-machine-learning/schnetpack] AttributeError: 'Namespace' object has no attribute 'features' (Issue #362)





 
I think the training should basically be the same as with SchNet.
 What is the new error, that you are getting?
  
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Stefaanhess** [comment]
The picture is still missing. I think you might have to use the web interface in order to upload pictures.

**Comment by loilisxka** [comment]
![QQ截图20211102173730](https://user-images.githubusercontent.com/43001784/139824324-2280e817-e155-4443-bb9a-50e7eb051ee7.png)
This is the problem I encountered

**Comment by Stefaanhess** [comment]
Ok, now I can see it :)
Your script tries to restore a checkpoint somehow. You would need to change/remove the old `model_dir`. Or you can also use the `--overwrite` flag. This will overwrite old model directories.

**Comment by loilisxka** [comment]
Now the script can run normally,
thank you very much :)

**Comment by Stefaanhess** [comment]
Ok, perfect!
