### ISSUE TITLE
line magic function not found

### ISSUE THREAD

**Issue by phuongpho** [atomistic-machine-learning/schnetpack#364]
Hi, 
I tried to follow tutorial_01 and encounter this error when running the below cell:

%rm './new_dataset.db'
new_dataset = AtomsData('./new_dataset.db')
new_dataset.add_systems(atom)

It say the line magic function %rm is not found. Is there another way to create an empty database? 

Thanks

**Comment by ktschuett** [comment]
This is just the command to remove the file if it exists. You can just remove the line and make sure you do not have an existing file `./new_dataset.db`.
