### ISSUE TITLE
Reproduce results for PaiNN

### ISSUE THREAD

**Issue by chao1224** [atomistic-machine-learning/schnetpack#371]
Hi there,

Thank you for providing such a nice code base. I'm trying to reproduce the results for PaiNN on QM9, but failed on several tasks.

Can we help share the hyper-parameters for reproducibility?

Regards,
Shengchao

**Comment by ktschuett** [comment]
Sorry for the long wait, missed my issue notification were switched off. For reproducability of the paper results on QM9, you can have a look at the code in the paper supplement: https://proceedings.mlr.press/v139/schutt21a.html

**Comment by chao1224** [comment]
Hi, would be great if you can provide the full script or model weight for reproducing that. Now we are running [this example script](https://github.com/atomistic-machine-learning/schnetpack/blob/dev/src/examples/qm9_example.py), but still seems to be worse than the reported numbers.
