### ISSUE TITLE
Might be nice to see a SchNet submission for matbench

### ISSUE THREAD

**Issue by sgbaird** [atomistic-machine-learning/schnetpack#379]
> Matbench is an ImageNet for materials science; a curated set of 13 supervised, pre-cleaned, ready-to-use ML tasks for benchmarking and fair comparison. The tasks span a wide domain of inorganic materials science applications including electronic, thermodynamic, mechanical, and thermal properties among crystals, 2D materials, disordered metals, and more.
> 
> The Matbench python package provides everything needed to use Matbench with your ML algorithm in ~10 lines of code or less.

https://matbench.materialsproject.org/ (I'm unaffiliated)

**Comment by ktschuett** [comment]
I'll keep that in mind for the next SchNetPack version. Probably not SchNet though, but rather PaiNN or better
