### ISSUE TITLE
Warning for TorchEnvironmentProvider

### ISSUE THREAD

**Issue by omidshy** [atomistic-machine-learning/schnetpack#384]
I receive this warning:

```
UserWarning: where received a uint8 condition tensor. This behavior is deprecated and will be removed in a future version of PyTorch. Use a boolean condition instead.
```
for this line:

https://github.com/atomistic-machine-learning/schnetpack/blob/cf962385e32e7335ce3b3f34cd776a4b38c3d985/src/schnetpack/environment.py#L217

The following would probably fix it:

```
num_repeats = torch.where(pbc.bool(), num_repeats, torch.zeros_like(num_repeats))
```

**Comment by Stefaanhess** [comment]
Hey @omidshy ,
thanks for your message and sorry for the late reply.
You are right about the warning and the fix works out well. I will update the master branch!
