### ISSUE TITLE
It doesn't work normal on single node multi-GPU card 

### ISSUE THREAD

**Issue by zhoujingyu13687306871** [atomistic-machine-learning/schnetpack#392]
I referred document and wanted to use multiple GPUs run the script, but I found that only one GPU could work properly, and the rest of the GPU-Util were 0% 
part of the scripts are as follows:

if torch.cuda.is_available():
     device = "cuda"
   else:
     device = "cpu"

 # determine number of epochs and train
 n_epochs = 300
 trainer.train(device=device, n_epochs=n_epochs)

**Comment by ktschuett** [comment]
You have to wrap your model using DataParallel (see https://pytorch.org/docs/stable/generated/torch.nn.DataParallel.html). If you use the command-line interface with `spk_run.py`, this happens automatically if you set `--parallel`.
