### ISSUE TITLE
`neighborlist_md` `cutoff_shell` permits atoms to become closer than cutoff?

### ISSUE THREAD

**Issue by sirmarcel** [atomistic-machine-learning/schnetpack#397]
Hello,

When working on my own related code, I noticed that in your implementation of neighborlist caching, you use [this](https://github.com/atomistic-machine-learning/schnetpack/blob/50877d89e600f17632b3e3ceb8408954f3f1153e/src/schnetpack/md/neighborlist_md.py#L85) check to determine when to recompute: 

```python
torch.norm(self.previous_positions - positions, dim=1) > self.cutoff_shell
```

Shouldn't this be `0.5*self.cutoff_shell`? If two atoms are directly approaching each other, starting from a distance of `cutoff_full + epsilon = cutoff + cutoff_shell + epsilon`  and each can move as far as `cutoff_shell`, then they can come as close as `cutoff - cutoff_shell + epsilon`, so, if `epsilon` is `<= cutoff_shell`, then they will be not counted as neighbours even though they are closer than the actual cutoff. 

I have the same bug in my own code, and haven't noticed any significant impact from it, but in the interest of correctness, it may be good to look into this. I've attached a small script that moves two atoms closer than the cutoff without triggering a neighborlist recomputation, as example.

Cheers,

Marcel

***

```python
import torch
from ase import Atoms
from schnetpack.md import System
from schnetpack.md.neighborlist_md import NeighborListMD
from schnetpack.transform import ASENeighborList
from schnetpack import properties

cutoff = 5.0
shell = 0.5

atoms = Atoms(positions=[[0, 0, 0], [cutoff + 1.5 * shell, 0, 0]])

system = System()
system.load_molecules(atoms, position_unit_input=1.0)  # avoid unit conversion

# copied from from base_calculator.py

# Get atom types
atom_types = system.atom_types.repeat(1)

# Get n_atoms
n_atoms = system.n_atoms.repeat(system.n_replicas)

# Get positions
positions = system.positions.view(-1, 3)

# Construct index vector for all replicas and molecules
index_m = (
    system.index_m.repeat(system.n_replicas, 1)
    + system.n_molecules
    * torch.arange(system.n_replicas, device=system.device).long().unsqueeze(-1)
).view(-1)

# Get cells and PBC
cells = system.cells.view(-1, 3, 3)
pbc = system.pbc.repeat(system.n_replicas, 1, 1).view(-1, 3)

inputs = {
    properties.Z: atom_types,
    properties.n_atoms: n_atoms,
    properties.R: positions,
    properties.idx_m: index_m,
    properties.cell: cells,
    properties.pbc: pbc,
}

nl = NeighborListMD(cutoff=cutoff, cutoff_shell=shell, base_nbl=ASENeighborList)

print(nl.get_neighbors(inputs)["_idx_i_local"])

# move atoms by max allowed amount
inputs[properties.R][1, 0] -= shell
inputs[properties.R][0, 0] += shell

print(
    nl._update_required(positions=positions, cells=cells, idx_m=index_m, n_molecules=1)
)
print(nl.get_neighbors(inputs)["_idx_i_local"])
print((inputs[properties.R][0] - inputs[properties.R][1])[0] < cutoff)

```

which prints

```
tensor([], dtype=torch.int64)
tensor([False])
tensor([], dtype=torch.int64)
tensor(True)
```

on my machine with the up to date `dev` branch, indicating that the atoms are closer than the cutoff, but not recognised as such.

**Comment by mgastegger** [comment]
Hi Marcel,

thank you for bringing this to our attention, the factor 1/2 should be there and was missing.
I fixed this in the current dev branch.
