### ISSUE TITLE
Crash because of `should_rank_save_checkpoint` in `dev` branch

### ISSUE THREAD

**Issue by sklenard** [atomistic-machine-learning/schnetpack#410]
Hello,

I have been trying to use the `dev` branch but the training crashes after 1 epoch because `should_rank_save_checkpoint` property has been removed from `TrainingTypePlugin` since Pytorch Lightning 1.6.0:

```
    if self.trainer.training_type_plugin.should_rank_save_checkpoint:
AttributeError: 'SingleDeviceStrategy' object has no attribute 'should_rank_save_checkpoint'
```

 I think that the corresponding if statement in `_update_best_and_save()` (from `schnetpack.train.callbacks`) should be replaced by `self.trainer.strategy.local_rank == 0`, but you may have a better fix.

Cheers,

Benoit

**Comment by ktschuett** [comment]
Thank you for the report. I think I will replace the ModelCheckpoint together and replace it with one of the new Lightning IO plugins...
