### ISSUE TITLE
CUDA out of memory problem

### ISSUE THREAD

**Issue by luckyjackluo** [atomistic-machine-learning/schnetpack#422]
Hi, 

I am trying to train the model on a training set with about 20000 samples, each sample contains 256 water molecules (or 768 atoms) with periodic boundary condition. I built the dataset based on the instruction in the documentation and here is the information of it: 

Number of reference calculations: 21297
Available properties:
- energy
- force

Properties of molecule with id 0:
- energy : torch.Size([1])
- force : torch.Size([768, 3])
- _atomic_numbers : torch.Size([768])
- _positions : torch.Size([768, 3])
- _neighbors : torch.Size([768, 767])
- _cell : torch.Size([3, 3])
- _cell_offset : torch.Size([768, 767, 3])
- _idx : torch.Size([1])

I am using CentOS7 and the following is my gpu information:
`Mon Aug 15 15:47:46 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.39.01    Driver Version: 510.39.01    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:18:00.0 Off |                    0 |
| N/A   34C    P0    40W / 300W |      3MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:3B:00.0 Off |                    0 |
| N/A   33C    P0    40W / 300W |      0MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:86:00.0 Off |                    0 |
| N/A   39C    P0    41W / 300W |      0MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:AF:00.0 Off |                    0 |
| N/A   41C    P0    41W / 300W |      0MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
`

And I am getting CUDA out of memory error:
`RuntimeError: CUDA out of memory. Tried to allocate 1.41 GiB (GPU 0; 31.75 GiB total capacity; 29.21 GiB already allocated; 436.19 MiB free; 30.36 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

I am not sure if this means I should increase my gpu memory even more because this amount is probably all I got. I tried to reduce the batch size to even 1 but this problem still exists. Do you have any idea how to solve it?

Thank you!
Jack

**Comment by mgastegger** [comment]
It looks like you are using the default neighborlist (`SimpleEnvironmentProvider`). This neighborlist returns all possible interatomic distances independent of the cutoff radius (explaining the large size of the `_neighbors` and `_cell_offsets` arrays). This automatically results in a larger memory usage. Furthermore, the `SimpleEnvironmentProvider` cannot deal with PBCs if those are relevant for your system.

You can try using to the ASE neighborlist (`--environment_provider ase`) which does not suffer from these issues.

In general, I would recommend switching to the updated version of schnetpack in the `dev` branch, which has better performance and more features.
