### ISSUE TITLE
Eval mode of all scripts broken by torch.load

### ISSUE THREAD

**Issue by bartolsthoorn** [atomistic-machine-learning/schnetpack#44]
I think recently a change was made to save the model instead of the state as a checkpoint (which I agree is an improvement). Anyway, all scripts are still using `load_state_dict` instead of just `model = torch.load(...)`, so the scripts now give an error when running eval like: `AttributeError: 'DataParallel' object has no attribute 'copy'`.

**Comment by ktschuett** [comment]
Hm, that's weird. The checkpoints should still be saved as state_dict, and only the final, best model should be stored to be easily reusable in other scripts.

@Stefaanhess Can you check that?

**Comment by Stefaanhess** [comment]
Yes, I will have a look at it.
