### ISSUE TITLE
TypeError occurred when train models with the CLI

### ISSUE THREAD

**Issue by wangzai-zfw** [atomistic-machine-learning/schnetpack#440]
Hi SchNetPack development team,  

I'm currently learning the SchNet. Since I can't figure out how to add early stopping in python code, I attempt to modify the .yaml files in schnetpack/src/schnetpack/configs in order to train schnet model with early stopping. Could you please let me know how to add early stopping in python code if it's not too much trouble?

When I use CLI to train models, a TypeError occurred. The process I used to train a SchNet model with CLI is as follows:

I created two .yaml files in the two folders respectively. The names of the two folders are data and experiment in schnetpack/src/schnetpack/configs. The content of the following two TXT files is the .yaml file I created for the training model
[test_in_data.txt](https://github.com/atomistic-machine-learning/schnetpack/files/9679898/test_in_data.txt)
[test_in_experiment.txt](https://github.com/atomistic-machine-learning/schnetpack/files/9679899/test_in_experiment.txt)

The command I use is as follows：
`spktrain --config-dir=~/git/schnetpack/src/schnetpack/configs experiment=test_in_experiment.yaml model/representation=schnet > output_test_moldel_task.txt`

Then, a TypeError occurred. 
![image](https://user-images.githubusercontent.com/49906543/193170974-bdfa5493-f665-4730-9aa9-d182a3a87b0b.png)

The complete error output is in the following TXT file.
[error_output.txt](https://github.com/atomistic-machine-learning/schnetpack/files/9679982/error_output.txt)

Thank you in advance for any help you might be able to provide.

Best regards,
Wangzai

**Comment by ktschuett** [comment]
I tried your experiment config and it works for me (had to switch to a different data config thought, since I don't have your data). The error indicates that schnetpack tries to load an existing model. Maybe you have trained a model previously in the same directory and the checkpoints are not compatible?

As for your question about early stopping in code: since we are using pytorch lightning as a training framework now, you can apply their early stopping callback as described [here](https://pytorch-lightning.readthedocs.io/en/latest/common/early_stopping.html) .

**Comment by sssaennn** [comment]
> Hi SchNetPack development team,
> 
> I'm currently learning the SchNet. Since I can't figure out how to add early stopping in python code, I attempt to modify the .yaml files in schnetpack/src/schnetpack/configs in order to train schnet model with early stopping. Could you please let me know how to add early stopping in python code if it's not too much trouble?
> 
> When I use CLI to train models, a TypeError occurred. The process I used to train a SchNet model with CLI is as follows:
> 
> I created two .yaml files in the two folders respectively. The names of the two folders are data and experiment in schnetpack/src/schnetpack/configs. The content of the following two TXT files is the .yaml file I created for the training model [test_in_data.txt](https://github.com/atomistic-machine-learning/schnetpack/files/9679898/test_in_data.txt) [test_in_experiment.txt](https://github.com/atomistic-machine-learning/schnetpack/files/9679899/test_in_experiment.txt)
> 
> The command I use is as follows： `spktrain --config-dir=~/git/schnetpack/src/schnetpack/configs experiment=test_in_experiment.yaml model/representation=schnet > output_test_moldel_task.txt`
> 
> Then, a TypeError occurred. ![image](https://user-images.githubusercontent.com/49906543/193170974-bdfa5493-f665-4730-9aa9-d182a3a87b0b.png)
> 
> The complete error output is in the following TXT file. [error_output.txt](https://github.com/atomistic-machine-learning/schnetpack/files/9679982/error_output.txt)
> 
> Thank you in advance for any help you might be able to provide.
> 
> Best regards, Wangzai

Maybe you can try editing `self.save_hyperparameters(ignore=["model"])` to `self.save_hyperparameters()` in [task.py](https://github.com/atomistic-machine-learning/schnetpack/blob/master/src/schnetpack/task.py)

**Comment by ktschuett** [comment]
Ok, there seems to be a problem with the hyperparameter storage of pytorch lightning: If ``ignore=["model"]`` is set, saving/loading of models does not work properly, but if it is not set then logging crashes when not using the CLI. I will try to find a workaround...
