### ISSUE TITLE
New release of schnetpack on PyPI?

### ISSUE THREAD

**Issue by chgaul** [atomistic-machine-learning/schnetpack#449]
Dear schnetpack developers!

I am about to publish some code that uses schnetpack. It requires commit 7a665f1, which has been on the master for some time, but is ahead of the latest released version 1.0.0 on PyPI.
Would it be possible to have a new PyPI release soon, including commit 7a665f1 (but no breaking changes, please)? That would help te keep my dependencies simple.

With kind regards,
Christopher Gaul

**Comment by ktschuett** [comment]
It seems the PR came in just after the last release and got lost. I created a release 1.0.1 with the couple of changes that happened after the last release.

Best,
Kristof

**Comment by chgaul** [comment]
Thank you for the quick solution!
