### ISSUE TITLE
Setting the model for our own data.

### ISSUE THREAD

**Issue by Dipannoy** [atomistic-machine-learning/schnetpack#452]
I have prepared our own dataset with ASEAtomsData class. Our dataset contains crystal structures and corresponding properties. Basically, it can be compared with the MaterialsProject class of schnetapack dataset. Initially, I tried to treat our dataset as a MaterialsProject object. However, it couldn't find the keys(properties) when the setup() method is called though I have modified the Materials Project class. After that, I tried with ASEAtomsData to make it compatible for the neural network model but couldn't run the model due to an inheritance problem(**ValueError: Expected a parent**). 

Could you please suggest any references to run our own dataset with schnetpack models so that I could understand my mistakes?

**Comment by ktschuett** [comment]
I can only guess here, since I did not see your code. If you have already parsed your data (e.g. as described [here](https://schnetpack.readthedocs.io/en/latest/tutorials/tutorial_01_preparing_data.html)), you should directly you ``AtomsDataModule``, not one of the predefined datasets.
