### ISSUE TITLE
Using Gpu While Training module (Tutorial_02)

### ISSUE THREAD

**Issue by koushik-bug** [atomistic-machine-learning/schnetpack#484]
I have set two parameter to utilised GPU power while training- 
trainer = pl.Trainer(
    **accelerator='gpu', 
    devices=1,**
    callbacks=callbacks,
    logger=logger,
    default_root_dir=qm9tut,
    max_epochs=3, # for testing, we restrict the number of epochs
)
Got the following error- RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)
Could you please suggest how to resolve the following error?

**Comment by koushik-bug** [comment]
I have used-
 model = torch.load( "model_path", map_location="cpu")
And the issue disappeared.

**Comment by ignaciomigliaro** [comment]
I have the same issue, but in your solution you just turned off the GPU usage, have you found a way to run GPU's and not have error?
