### ISSUE TITLE
Tutorial 03, md17 data set not found

### ISSUE THREAD

**Issue by koushik-bug** [atomistic-machine-learning/schnetpack#485]
I was tring to run tutotial_03.
Got the following error while running the first part of the code-

**INFO:root:Downloading ethanol data
.
.
.
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found**

I think the URL in not valid to download the MD17 file.
Any suggetion?

**Comment by mgastegger** [comment]
Are you using the the latest version of SchNetPack?
It seems that the MD17 download URLs changed and we fixed this in a recent PR (see PR #483).

**Comment by koushik-bug** [comment]
Thanks for the suggetions. It seems like I have used  an week older version. Now everything work perfectly.
