### ISSUE TITLE
Positions in the custom dataset conflict with original geometry 

### ISSUE THREAD

**Issue by Neon7799** [atomistic-machine-learning/schnetpack#488]
Hi, I'm preparing the .db file using my own dataset(.xyz file)

Below is the xyz position of the first 10 atoms for a given molecule:

- This is the xyz postions from schnetpack

<img width="1142" alt="Screenshot 2023-01-25 at 11 38 54 AM" src="https://user-images.githubusercontent.com/56499422/214623258-5ce769ed-e999-4af7-8eaf-055f50f5f787.png">

- This is my original geometry of the same molecule

<img width="462" alt="Screenshot 2023-01-25 at 11 39 39 AM" src="https://user-images.githubusercontent.com/56499422/214623267-5c68e357-b340-494d-b1e4-e15eb281cdb0.png">

They're not exactly the same. I'm wondering what's the possible reason. Thanks.

**Comment by mgastegger** [comment]
Hi, it appears you are using the old version of SchNetPack. There, the datasets have an option `centering_function` which can be used to set the center (origin) of the Cartesian coordinates when writing to the database. In the old SchNetPack, this is set to move the origin of the coordinate system to the center of mass. I assume this is what happens in your case. It should be easy to check. 

If this effect is undesired, you can add the option `centering_function=False` to the `AtomsData` call.
In general, we would recommend switching to the new SchNetPack version though.

**Comment by Neon7799** [comment]
Thanks, it solved. Yes, I'm using schnetpack 1.0 since I want to try symmetry function. I will switch to the newest version later.
