### ISSUE TITLE
Error while using Materials database. 

### ISSUE THREAD

**Issue by ignaciomigliaro** [atomistic-machine-learning/schnetpack#496]
Hello when trying to run the Materials database dataset, I encounter the follow error: 

/scratch/.conda/envs/MLFF-python38/lib/python3.8/site-packages/schnetpack/---------------------------------------------------------------------------
MPRestError                               Traceback (most recent call last)
File /scratch/.conda/envs/MLFF-python38/lib/python3.8/site-packages/pymatgen/ext/matproj.py:278, in MPRester._make_request(self, sub_url, payload, method, mp_decode)
    276         raise MPRestError(data["error"])
--> 278     raise MPRestError(f"REST query returned with error status code {response.status_code}")
    280 except Exception as ex:

MPRestError: REST query returned with error status code 403

During handling of the above exception, another exception occurred:

MPRestError                               Traceback (most recent call last)
Cell In[22], line 15
      5 #apikey="ASVDNR1BcvRXSuyIMpIboXCytVLMUmO6"
      7 MP = MaterialsProject(
      8     './materialsproject.db', 
      9     apikey=apikey,
   (...)
     13     num_workers=2,
     14 )
---> 15 MP.prepare_data()
     16 MP.setup()

File /scratch/.conda/envs/MLFF-python38/lib/python3.8/site-packages/schnetpack/datasets/materials_project.py:124, in MaterialsProject.prepare_data(self)
    110     property_unit_dict = {
    111         MaterialsProject.EformationPerAtom: "eV",
    112         MaterialsProject.EPerAtom: "eV",
    113         MaterialsProject.BandGap: "eV",
    114         MaterialsProject.TotalMagnetization: "None",
    115     }
    117     dataset = create_dataset(
    118         datapath=self.datapath,
    119         format=self.format,
    120         distance_unit="Ang",
    121         property_unit_dict=property_unit_dict,
    122     )
--> 124     self._download_data(dataset)
    125 else:
    126     dataset = load_dataset(self.datapath, self.format)

File /scratch/.conda/envs/MLFF-python38/lib/python3.8/site-packages/schnetpack/datasets/materials_project.py:157, in MaterialsProject._download_data(self, dataset)
    155 for nsites in range(0, 300, 30):
    156     ns = {"$lt": nsites + 31, "$gt": nsites}
--> 157     query = m.query(
    158         criteria={
    159             "nelements": N,
    160             "is_compatible": True,
    161             "nsites": ns,
    162         },
    163         properties=[
    164             "structure",
    165             "energy_per_atom",
    166             "formation_energy_per_atom",
    167             "total_magnetization",
    168             "band_gap",
    169             "material_id",
    170             "warnings",
    171             "created_at",
    172         ],
    173     )
    174     for k, q in enumerate(query):
    175         if (
    176             self.timestamp is not None
    177             and q["created_at"] > self.timestamp
    178         ):

File /scratch/.conda/envs/MLFF-python38/lib/python3.8/site-packages/pymatgen/ext/matproj.py:1026, in MPRester.query(self, criteria, properties, chunk_size, max_tries_per_chunk, mp_decode, show_progress_bar)
   1024 count_payload = payload.copy()
   1025 count_payload["options"] = json.dumps({"count_only": True})
-> 1026 num_results = self._make_request("/query", payload=count_payload, method="POST")
   1027 if num_results <= chunk_size:
   1028     return self._make_request("/query", payload=payload, method="POST", mp_decode=mp_decode)

File /scratch/.conda/envs/MLFF-python38/lib/python3.8/site-packages/pymatgen/ext/matproj.py:282, in MPRester._make_request(self, sub_url, payload, method, mp_decode)
    280 except Exception as ex:
    281     msg = f"{ex}. Content: {response.content}" if hasattr(response, "content") else str(ex)
--> 282     raise MPRestError(msg)

MPRestError: REST query returned with error status code 403. Content: b'{"valid_response": false, "error": "API_KEY is not a valid key.", "version": {"db": "2020_09_08", "pymatgen": "2022.0.8", "rest": "2.0"}, "created_at": "2023-02-22T09:05:25.776812"}'

I have made sure that the APIkey is correct and it works with using the standard summary.search with MPRester. Here is the sample of my code. 

MP = MaterialsProject(
    './materialsproject.db', 
    apikey=apikey,
    batch_size=10,
    num_train=100000,
    num_val=25000,
    num_workers=2,
)
MP.prepare_data()
MP.setup()

Thanks!

**Comment by Stefaanhess** [comment]
Hi @ignaciomigliaro ,
sorry for the late reply!
It seems like Materials project updated their API and there are currently two different kinds of API keys.
We still use the legacy API, which is recommended by Materials Project and therefore you would need to generate the API-key with the legacy API website (https://legacy.materialsproject.org/open). The legacy API-key should have 16 characters, while the new API-keys should have 32 characters.
Let me know if this solves the issue.

**Comment by ignaciomigliaro** [comment]
> Hi @ignaciomigliaro , sorry for the late reply! It seems like Materials project updated their API and there are currently two different kinds of API keys. We still use the legacy API, which is recommended by Materials Project and therefore you would need to generate the API-key with the legacy API website (https://legacy.materialsproject.org/open). The legacy API-key should have 16 characters, while the new API-keys should have 32 characters. Let me know if this solves the issue.

Thank you for answering, so I was using the legacy API but for some reason it was not the correct character length, so I regenerated the key, and that time it worked. Thanks!
