### ISSUE TITLE
Advice on HP tuning

### ISSUE THREAD

**Issue by LeonardoBarneschi** [atomistic-machine-learning/schnetpack#516]
Hi everyone.
I trying to use SchNet to calculate properties of dimers, which in my case are far more dependent on intermolecular interactions between the two monomers than intramolecular interactions. I think I must make sure that the cutoff is such that in the embedding of the atom of one monomer, I have atoms from the other monomer. This can be sort of troublesome when the distance between the two monomers increases, since to account for this, I will probably end up including all possible pairwise distances, increasing the complexity of the model and the computational cost by quite a lot.

So, I was wondering, what is the best way to deal with such a scenario? Do you have some general recommendation? 

Thank you in advance,
Leo

**Comment by jnsLs** [comment]
Dear @LeonardoBarneschi,
we have a transform implemented that allows to do that: ./src/schnetpack/transform/neighborlist.py --> FilterNeighbors
However, this class was originally designed for a different purpose and we do not recommend using it the way you proposed. We expect that excluding intramolecular interactions would impair the representation learning drastically even if the electronic properties mostly depend on intermolecular interactions.
Best regards, Jonas

**Comment by LeonardoBarneschi** [comment]
Dear @jnsLs. Thank you very much for the information.  I really appreciate it. 
For me you can close this thread.
