### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by ktschuett** [atomistic-machine-learning/schnetpack#52]
- [x] Add missing doc strings
- [x] Write tutorials
- [x] Include into main doc (index.rst)

You can check the results at https://schnetpack.readthedocs.io/en/latest/

**Comment by Dekken** [comment]
Can you provide a complete schnet training command based on the git repo and test data please?

**Comment by Dekken** [comment]
```
python3 src/scripts/schnetpack_qm9.py train schnet . .  --split 10 10 --cuda
INFO:root:Random state initialized with seed 4076610638
INFO:root:QM9 will be loaded...
INFO:schnetpack.data.atoms:The dataset has already been downloaded and stored at .
Traceback (most recent call last):
  File "src/scripts/schnetpack_qm9.py", line 397, in <module>
    atomref = qm9.get_atomref(train_args.property)
  File "/home/philix/.pyenv/versions/3.7.2/lib/python3.7/site-packages/schnetpack-0.2.1-py3.7.egg/schnetpack/data/atoms.py", line 241, in get_atomref
  File "/home/philix/.pyenv/versions/3.7.2/lib/python3.7/site-packages/schnetpack-0.2.1-py3.7.egg/schnetpack/data/atoms.py", line 131, in get_metadata
  File "/home/philix/.pyenv/versions/3.7.2/lib/python3.7/site-packages/ase-3.17.0-py3.7.egg/ase/db/core.py", line 149, in connect
    raise ValueError('No file extension or database type given')
ValueError: No file extension or database type given
```

**Comment by ktschuett** [comment]
Hi, I updated the tutorial and command-line help. The command has to point to the .db file:
python3 src/scripts/schnetpack_qm9.py train schnet ./qm9.db .  --split 10 10 --cuda

**Comment by machism0** [comment]
This should also be reflected in the readme, right now it suggests an argument of "datadir" not "datadir.db"

**Comment by dumkar** [comment]
I had the same error when running 

`spk_run.py train schnet qm9 ./spk_data/qm9 ./spk_model/ --split 10000 1000`

Which resolves when inclding .db in the datadir:

`spk_run.py train schnet qm9 ./spk_data/qm9.db ./spk_model/ --split 10000 1000`

The README mentions <datadir> and not <datadir.db>

**Comment by Stefaanhess** [comment]
I updated the README. Hope this helps
