### ISSUE TITLE
JCTC paper training example

### ISSUE THREAD

**Issue by MartinEls** [atomistic-machine-learning/schnetpack#54]
Thanks a lot for the great code!

If I tried to run the training example from the paper (Chart 1), I got some errors. If the ´import´ section should stay untouched the following lines should be changed to:
'''
15: loader = spk.data.AtomLoader...
18: val_loader = spk.data.AtomsLoader...
28: trainer = spk.train.Trainer...

**Comment by ktschuett** [comment]
Thanks, should be fixed now.
