### ISSUE TITLE
Questions on LAMMPS interfaces

### ISSUE THREAD

**Issue by ZKC19940412** [atomistic-machine-learning/schnetpack#542]
Dear developers of shnetpack:

Hi. Thank you all so much for making the LAMMPS interface workable with shnetpack. I have three questions relating the LAMMPS interface:

1. Does the interface work for periodic systems, if so, do you all mind providing one in the example folder?
2. Does the interface work only under real unit? 
3. When I played around with the aspirin example, I saw the mass for each type of atom was set to 1.0, is there a reason why the mass has to be set this way?

Thank you so much for answering my questions. 

Best, 
Zekun

**Comment by jnsLs** [comment]
Dear Zekun,

thank you for your questions.

1. Our interface works for periodic systems. To achieve this, you just have to adapt the *.in and *.data file for LAMMPS. In this case, there should be no difference in the workflow between default LAMMPS pair styles and the schnetpack pairstyle. We don't have an example we can provide immediately, but we plan to work on that. 
2. you can use any unit style, depending on your input data file and your model output. In our case, the structure in aspirin.data is given in Angstrom and our energy outputs are in kcal/mol. Thus, we use real units.
3. regarding the masses. This might be a mistake we made. I think it should be the mass of Carbon, Hydrogen and Oxygen in gram/mol. We will look into this and, if needed, update the input file.

Best, Jonas

**Comment by sonti9215** [comment]
Dear Jonas, 

I tried running the LAMMPS simulation of aspiring using periodic conditions and the updated masses and the simulation runs. 

Best, Siddharth

**Comment by JakechiC** [comment]
Dear developers,

I am delighted that your work has been of great help and inspiration to me. While reading your paper on PAINN, I was able to reproduce the results, which made me even happier. However, I have a question that I haven't quite grasped yet. How does PAINN achieve equivariance? In its input, there are vectors rij, which can vary in different coordinate systems. Nevertheless, this network is equivariant. Could you kindly help me understand this concept? Thank you very much for taking the time to answer my question.

Best regards,

JakechiC
