### ISSUE TITLE
'ASEAtomsData' object has no attribute 'prepare_data_per_node'

### ISSUE THREAD

**Issue by hekaido** [atomistic-machine-learning/schnetpack#556]
After making a custom dataset using tutorial in git, and further trying to traing schnet to predict atom energy i get this exception
AttributeError: 'ASEAtomsData' object has no attribute 'prepare_data_per_node'

**Comment by jnsLs** [comment]
Hi @hekaido ,
could you please provide more information?
In particular, how exactly are you training schnet?
In case you are using a config file, please provide that to us. 
Furthermore, it would be helpful if you could provide information about the installed packages in your python environment. In particular pytorch-lightning, pytorch, and ase.
Best, Jonas

**Comment by hekaido** [comment]
Hi @jnsLs 
At first I have structures parsed from aflow dataset. I'm creating a custom dataset using tutorial at 
examples/tutorials/tutorial_01_preparing_data.ipynb. Then I use a examples/tutorials/tutorial_03_force_models.ipynb to train a schnet for predicting energy of parsed structures. The problem occurs after trying to start training with pytorch-lightning trainer module and proving as datamodule argument my custom dataset
trainer.fit(task, datamodule=new_dataset)
AttributeError: 'ASEAtomsData' object has no attribute 'prepare_data_per_node'
You can checkout my notebook for further information:
https://colab.research.google.com/drive/1KI3jABjEmcYQAsjs5hU4MEhzLdMKz9j5?usp=sharing

**Comment by jnsLs** [comment]
In general, training models is easier using the command line interface (CLI) described in the README.md file.
Best, Jonas

**Comment by hekaido** [comment]
Thx a lot @jnsLs , I will try this on!!

**Comment by sgugler** [comment]
> Hi @hekaido , for training you should use `spk.data.AtomsDataModule` instead of `ASEAtomsData`. Here is a template:
> ...

FWIW, I had the same issue today and this solved it.

**Comment by Stefaanhess** [comment]
We updated (#562 ) the tutorial. I hope it is more clear now!
