### ISSUE TITLE
Mismatched tensor sizes: 

### ISSUE THREAD

**Issue by ignaciomigliaro** [atomistic-machine-learning/schnetpack#563]
Hello, currently I am trying to train on solid state data, I am getting an error with mismatched tensor sizes: 

File "/scratch/.conda/envs/schnetpack/lib/python3.10/site-packages/torch/functional.py", line 74, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore[attr-defined]
RuntimeError: The size of tensor a (3) must match the size of tensor b (30) at non-singleton dimension 1

When I create the .db file, I printed the shape size are: 
Properties of molecule with id 0:
- _idx : torch.Size([1])
- energy : torch.Size([1])
- forces : torch.Size([30, 3])
- stress : torch.Size([3, 3])
- _n_atoms : torch.Size([1])
- _atomic_numbers : torch.Size([30])
- _positions : torch.Size([30, 3])
- _cell : torch.Size([1, 3, 3])
- _pbc : torch.Size([3])

Attached is my config file.
[forces.txt](https://github.com/atomistic-machine-learning/schnetpack/files/12362189/forces.txt)

Thanks.

**Comment by jnsLs** [comment]
Hi @ignaciomigliaro ,

could you please provide the full error message? And which model are you training? SchNet, PaiNN, FieldSchNet, ...?

It looks like the dimension of stress is wrong. Could you try expanding it by the batch size? In your example case (of molecule 0) this would be 1x3x3 instead of 3x3.

Best, Jonas

**Comment by jnsLs** [comment]
We have updated (#564) the tutorial on materials to make clear which dimensions to use.
I hope this solves your problem.

**Comment by ignaciomigliaro** [comment]
Thank you so much that fixed the error, although I am having problem training it just dies on epoch 0 showing infinite error.

**Comment by jnsLs** [comment]
Can you provide more information on the error? Does it still presist?
