### ISSUE TITLE
What can also be used as input modules in the AtomisticTask for energy prediction except PairwiseDistances?

### ISSUE THREAD

**Issue by hekaido** [atomistic-machine-learning/schnetpack#565]
I'm trying to perform an energy prediction for structures from aflow dataset and I'm curious, if i can use more input modules than just spk.atomistic.PairwiseDistances
Can i use all modules from spk.atomistic?
If so, can you give me some examples of their usage?

**Comment by jnsLs** [comment]
The model architectures implemented in SchNetPack are designed to take pairwise distance (vectors) and atom types as inputs. The other modules in spk.atomistic are rather output modules.

**Comment by hekaido** [comment]
Thanks for your answer!
