### ISSUE TITLE
Conda installation problem

### ISSUE THREAD

**Issue by lizsalmon** [atomistic-machine-learning/schnetpack#570]
We have an issue with installing Schnetpack on anaconda.  

The commands we used (both have same error): 
conda install -c "conda-forge/label/cf202003" schnetpack
conda install -c conda-forge schnetpack

Output: 
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Is there a command that we should be using instead? 
Thank you.

**Comment by Stefaanhess** [comment]
Hey @lizsalmon ,
I am sure why it does not work with conda-forge. We will look into this.
We usually recommend to just use `pip install schnetpack`.
Is there a reason why pip does not work out for you?

**Comment by lizsalmon** [comment]
I'm not sure whether it is the installation but when installed using pip I can't run any of the schnetpack tutorials without errors.

**Comment by Stefaanhess** [comment]
This should not be the case! Could you maybe provide some more detailed information?
Preferably the traceback of your errors. Maybe I can spot what is going on
