### ISSUE TITLE
ASENeighborList in cuda

### ISSUE THREAD

**Issue by heyfavour** [atomistic-machine-learning/schnetpack#571]
new neighbor is too slow in cpu，can do ASENeighborList in cuda?

**Comment by jnsLs** [comment]
Dear @heyfavour,

At the moment, we do not provide neighbor lists that work on cuda.

However, you could use the MatScipyNeighborList, which is significantly faster than ASENeighborList. Furthermore depending on your task (e.g. MD or relaxations, not suitable for training) you can additionally use the SkinNeighborList.

Best, 
Jonas
