### ISSUE TITLE
invalid literal for int() with base 10: '*'

### ISSUE THREAD

**Issue by Rom4e6** [atomistic-machine-learning/schnetpack#577]
Hi, dear authors! 
 
Here I am trying to predict properties of given molecules, represented via SMILES.
Thus, I have to convert SMILES string into Atoms array, and I implemented the following code:

```
import numpy  as np

from ase import Atoms
from rdkit import Chem
from rdkit.Chem import AllChem

def ASE_Atoms_from_smile(SMILE):
    # try :
        mol = Chem.MolFromSmiles(SMILE, sanitize = False)
        mol = Chem.AddHs(mol,explicitOnly = True)
        AllChem.EmbedMolecule(mol)
        atom_and_coords = Chem.MolToXYZBlock(mol).split()[1:] 
        # print(atom_and_coords[::])

        keys = ['N', 'C', 'F', 'O', 'H', 'Cl']
        values = [7, 6, 9, 8, 1, 17]
        e2n = dict(zip(keys,values))
        atoms = atom_and_coords[::4]
        atoms = np.array([e2n.get(item,item) for item in atoms])

        x, y, z = np.float64(atom_and_coords[1::4]), np.float64(atom_and_coords[2::4]), np.float64(atom_and_coords[3::4])
        data = np.array([[a,b,c] for a,b,c in zip(x,y,z)])

        ats = Atoms(positions = data, numbers = atoms)
    
        return ats
    # except Exception as e :
        print(e)
        return 0

print(ASE_Atoms_from_smile("[H]C([H])([H])C"))  
```

Which works well until I do not operate on polymers SMILES, like : 

['*C=CCC(CC*)(C(=O)OC)C',
'*Oc1ccc2c(c1)nc1n2C(=O)c2ccc(-c3ccc4c(c3)C(=O)n3c-4nc4ccc(*)cc43)cc2-1',
'*c1ccc(Oc2ccc(Oc3ccc(N4C(=O)c5cccc(Oc6cccc7c6C(=O)N(*)C7=O)c5C4=O)cc3)cc2)cc1']

It falls with the error : 'invalid literal for int() with base 10: '*' '

Thus, the question is how to handle this polymer SMILES to deal with it via SchNetPack.

Sincerely,
Roman

**Comment by Rom4e6** [comment]
Hi, Jonas!

Thank you for your quick reply!

Unfortunately, the raised issue is underlined in SchNetPack, according to this traceback: 

```


ValueError                                Traceback (most recent call last)
Cell In[577], line 1
----> 1 from_radon_.iloc[:3].smiles.apply(ASE_Atoms_from_smile)

File ~/anaconda3/envs/SchNet/lib/python3.8/site-packages/pandas/core/series.py:4630, in Series.apply(self, func, convert_dtype, args, **kwargs)
   4520 def apply(
   4521     self,
   4522     func: AggFuncType,
   (...)
   4525     **kwargs,
   4526 ) -> DataFrame | Series:
   4527     """
   4528     Invoke function on values of Series.
   4529 
   (...)
   4628     dtype: float64
   4629     """
-> 4630     return SeriesApply(self, func, convert_dtype, args, kwargs).apply()

File ~/anaconda3/envs/SchNet/lib/python3.8/site-packages/pandas/core/apply.py:1025, in SeriesApply.apply(self)
   1022     return self.apply_str()
   1024 # self.f is Callable
-> 1025 return self.apply_standard()

File ~/anaconda3/envs/SchNet/lib/python3.8/site-packages/pandas/core/apply.py:1076, in SeriesApply.apply_standard(self)
   1074     else:
   1075         values = obj.astype(object)._values
-> 1076         mapped = lib.map_infer(
   1077             values,
   1078             f,
   1079             convert=self.convert_dtype,
   1080         )
   1082 if len(mapped) and isinstance(mapped[0], ABCSeries):
   1083     # GH#43986 Need to do list(mapped) in order to get treated as nested
   1084     #  See also GH#25959 regarding EA support
   1085     return obj._constructor_expanddim(list(mapped), index=obj.index)

File ~/anaconda3/envs/SchNet/lib/python3.8/site-packages/pandas/_libs/lib.pyx:2834, in pandas._libs.lib.map_infer()

Cell In[574], line 22, in ASE_Atoms_from_smile(SMILE)
     19     x, y, z = np.float64(atom_and_coords[1::4]), np.float64(atom_and_coords[2::4]), np.float64(atom_and_coords[3::4])
     20     data = np.array([[a,b,c] for a,b,c in zip(x,y,z)])
---> 22     ats = Atoms(positions = data, numbers = atoms)
     24     return ats
     25 # except Exception as e :

File ~/anaconda3/envs/SchNet/lib/python3.8/site-packages/ase/atoms.py:202, in Atoms.__init__(self, symbols, positions, numbers, tags, momenta, masses, magmoms, charges, scaled_positions, cell, pbc, celldisp, constraint, calculator, info, velocities)
    200             natoms = 0
    201         numbers = np.zeros(natoms, int)
--> 202     self.new_array('numbers', numbers, int)
    203 else:
    204     if numbers is not None:

File ~/anaconda3/envs/SchNet/lib/python3.8/site-packages/ase/atoms.py:456, in Atoms.new_array(self, name, a, dtype, shape)
    451 """Add new array.
    452 
    453 If *shape* is not *None*, the shape of *a* will be checked."""
    455 if dtype is not None:
--> 456     a = np.array(a, dtype, order='C')
    457     if len(a) == 0 and shape is not None:
    458         a.shape = (-1,) + shape

ValueError: invalid literal for int() with base 10: '*'
```
However, RDkit is able to handle such polymer SMILES

**Comment by epens94** [comment]
Hi Roman,

I was not able to reproduce your exact error using (rdkit version 2022.09.5, ase version 3.22.1)
But when using other SMILES I noticed that the output of the below line of your code

`        atoms = np.array([e2n.get(item,item) for item in atoms])`

results in a mixed type array of something like 
['6' '6' '6' '6' '6' '6' '6' '6' '6' '7' '6' '8' '6' 'S' '6'] ......

**Comment by Rom4e6** [comment]
Sure, to avoid mixed arrays one have to extend symbols dict with corresponding element number in periodic table.

from rdkit import Chem
from rdkit.Chem import AllChem


def ASE_Atoms_from_smile(SMILE):
    try :
        SMILE = SMILE.replace('*','C')
        mol = Chem.MolFromSmiles(SMILE, sanitize = False)
        mol = Chem.AddHs(mol,explicitOnly = True)
        AllChem.EmbedMolecule(mol)
        atom_and_coords = Chem.MolToXYZBlock(mol).split()[1:] 
        # print(atom_and_coords[::])

        keys = ['N', 'C', 'F', 'O', 'H', 'Cl', 'I', 'S', 'Br', 'P']
        values = [7, 6, 9, 8, 1, 17, 53, 16, 35, 15]
        e2n = dict(zip(keys,values))
        atoms = atom_and_coords[::4]
        atoms = np.array([e2n.get(item,item) for item in atoms])

        x, y, z = np.float64(atom_and_coords[1::4]), np.float64(atom_and_coords[2::4]), np.float64(atom_and_coords[3::4])
        data = np.array([[a,b,c] for a,b,c in zip(x,y,z)])

        ats = Atoms(positions = data, numbers = atoms)
    
        return ats
    except Exception as e :
        print(SMILE)
        print(e)
        return 0

print(ASE_Atoms_from_smile("[H]C([H])([H])C"))

This function can handle SMILES containing atoms from given list : ['N', 'C', 'F', 'O', 'H', 'Cl', 'I', 'S', 'Br', 'P'].
However, the question was about how to process polymer SMILES  with symbol '*' in them, without any replacements.
SMILES like : '*CC(*)c1ccc(C#N)cc1'

**Comment by Rom4e6** [comment]
Also I wonder how to add property without property_unit and distance_unit?

**Comment by jnsLs** [comment]
Hi Roman, 

I am starting to understand your problem now. As far as I know "*" is a placeholder for anything. You could 
1) replace "*" by an atomic number that is different from all the other available types in your data. For example 47 since you probably don't have any Ag atom in your dataset. 
2) remove "*" from the atomic numbers and the corresponding positions
3) saturate the molecule with Hydrogens

However, having unknown elements will always put a lot of noise on your model predictions. 

You can add unitless properties by setting the corresponding property_unit as an empty string. We do this in tutorial_05_materials.ipynb for the `considered_atoms` property.

Best, Jonas
