### ISSUE TITLE
qm9 needs remove_uncharacterized=False now?

### ISSUE THREAD

**Issue by Maltimore** [atomistic-machine-learning/schnetpack#587]
The examples in the Readme typically result in an error: One has to add `data.remove_uncharacterized=False` for them to run properly. I am not sure whether just the Readme should be updated, or whether this is a more fundamental problem that should be fixed elsewhere?

**Comment by jnsLs** [comment]
At some point the default setting in the dataloader changed. Have you tried removing your QM9.db file and running the training again?

**Comment by Maltimore** [comment]
Your suggestion worked, sorry for the noise!

**Comment by Maltimore** [comment]
Closing as this is not actually an issue.
