### ISSUE TITLE
Problems during training

### ISSUE THREAD

**Issue by MasterLucas** [atomistic-machine-learning/schnetpack#613]
Dear SchNetPack developers,

I am facing some problems training SchNet on the QM9 dataset according to the instructions in the docs. When I use the specified command "_$ spktrain experiment=qm9_atomwise_", the following error is raised:

_TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead._

Could you please help me with this?

Yours faithfully,

**Comment by jnsLs** [comment]
Dear Lucas, 

seems like you are using a MAC. If you don't have the option to run SchNetPack on a computation cluster or a cloud service, the easiest option should be disabling your GPU and train on the CPU instead.

Best, 
Jonas

**Comment by MasterLucas** [comment]
Dear Jonas, 

Thank you very much for your reply and help. I managed to run SchNetPack both in the cloud and on a supercomputer. However, I am still a bit confused about what happened. I am using a Mac, but there is no GPU in it. Could you think of another reason for this error and how I could solve it? 

Yours sincerely,

Lucas Bandeira

**Comment by jnsLs** [comment]
Hi Lucas,

have you tried adding the argument `trainer.accelerator=cpu` ?

**Comment by MasterLucas** [comment]
Now it works!

Thank you very much, Jonas!
