### ISSUE TITLE
Atomic energies

### ISSUE THREAD

**Issue by rothjo** [atomistic-machine-learning/schnetpack#635]
Hi,
is there a way to obtain atomic-wise energies from a SchNet?

Best, Jonas

**Comment by jnsLs** [comment]
Hi Jonas, 

yes, you just need to specify a `per_atom_output_key` for the `schnetpack.atomistic.Atomwise` output module.

Best, Jonas

**Comment by rothjo** [comment]
Hi again,

ok perfect, thanks for the quick answer.

Best, Jonas
