### ISSUE TITLE
Model Testing

### ISSUE THREAD

**Issue by MasterLucas** [atomistic-machine-learning/schnetpack#637]
Dear Sir/ Madam, 

I have a question about testing a trained model. I know I can specify the number of examples I want to use for testing when creating the dataset using the `spk.data.AtomsDataModule`.  However, suppose I am training a set of different models, for instance, to compare their performance with different training and validation splits. How could I ensure that the same examples are used for testing each model?

Yours faithfully, 

Lucas Bandeira

**Comment by MasterLucas** [comment]
Hi Jonas,

Thank you very much for your reply. What would be the most appropriate way to do this? Could I simply use `np.savez` to create the split files?

Yours sincerely,

Lucas Bandeira

**Comment by jnsLs** [comment]
Hi Lucas, 
using 'np.savez' is a valid way to do this :)
Best, Jonas

**Comment by MasterLucas** [comment]
Nice! Thank you very much, Jonas!
