### ISSUE TITLE
MPI error in lammps

### ISSUE THREAD

**Issue by SyntaxSmith** [atomistic-machine-learning/schnetpack#657]
I am trying to run a MD with a big reaction system use lammps. I catch two errors:
When I use `mpirun --mca btl tcp,self -np 4 lmp -k on g 4 -sf kk -in Au.in`,will have this error
[slurm-457981.txt](https://github.com/user-attachments/files/16745333/slurm-457981.txt)
When I use `mpirun --mca btl tcp,self -np 1 lmp -in Au.in -sf omp -pk omp 32`,will have 
[slurm-457974.txt](https://github.com/user-attachments/files/16745343/slurm-457974.txt)
only when I `export OMP_NUM_THREADS=1` the MD can run successfully. I don't know if schnetpack's lammps interface's limit or my compilation’s config's error

**Comment by stefaanhessmann** [comment]
Hi @wzy461143268
I am not sure if this is related to schnetpack. It seems that in [slurm-457974.txt](https://github.com/user-attachments/files/16745343/slurm-457974.txt), the model was successfully used to predict energies and forces. So maybe this is related to your system?
Have you tried to run the code with another potential?

**Comment by wzy461143268** [comment]
> Hi @wzy461143268 I am not sure if this is related to schnetpack. It seems that in [slurm-457974.txt](https://github.com/user-attachments/files/16745343/slurm-457974.txt), the model was successfully used to predict energies and forces. So maybe this is related to your system? Have you tried to run the code with another potential?

I'll try it
