### ISSUE TITLE
Reproducing ICML2021 QM9 gap results with CLI

### ISSUE THREAD

**Issue by ftherrien** [atomistic-machine-learning/schnetpack#674]
First of all, thanks for this great, well documented code base!

Should I expect to closely reproduce the results from the paper using the default CLI parameters?

I am running the following:

`spktrain experiment=qm9_dipole globals.property=gap data.num_workers=1`

I obtain:

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│       test_gap_mae        │    0.10996653139591217    │
│       test_gap_rmse       │    0.28789040446281433    │
│         test_loss         │    0.08288087695837021    │
└───────────────────────────┴───────────────────────────┘
```

The paper reports an MAE of 46 meV for this task. Is this normal? What arguments should I add to more closely reproduce this result.

**Comment by stefaanhessmann** [comment]
It seems like there is a bug with QM9 in the current version, as this issue is very similar to #672.

You could try to change the settings for `n_interactions`, `n_atom_basis` and the activation functions. However, it might be related to some other problem. We are currently looking into this by training some models ourselves.

**Comment by ftherrien** [comment]
I was able to obtain the following, which is close enough:

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│       test_gap_mae        │    0.04883946478366852    │
│       test_gap_rmse       │    0.08138106018304825    │
│         test_loss         │   0.0066228765062987804   │
└───────────────────────────┴───────────────────────────┘

```
Using the atomwise task instead. 

I created a config file identical to [qm9_atomwise.yaml](https://github.com/atomistic-machine-learning/schnetpack/blob/master/src/schnetpack/configs/experiment/qm9_atomwise.yaml) in `./config/experiment/myconfig.yaml` and I changed the following: property=gap, aggregation=mean, remove_atomrefs=False, add_atomrefs=False. Then, I ran:

`spktrain experiment=myconfig`

There is probably a way to specify that directly on the command line with hydra, but I could not figure it out.

**Comment by stefaanhessmann** [comment]
Thanks for the update!

I totally did not see that you were using the wrong config file, but I am happy that it works well now.
