### ISSUE TITLE
How can I use my own data in .lmdb format

### ISSUE THREAD

**Issue by SoFarN** [atomistic-machine-learning/schnetpack#677]
Hi, 
I am going to train ScheNet-based interatomic potential on my data which are in the binary format of .lmdb 
As I got error, I tried to copy the MD17 data and firstly test my script ( train_schnetpack.py) which you can find in the following. However, I get error (line 5, in <module>
    from schnetpack.output_modules import Atomwise
ModuleNotFoundError: No module named 'schnetpack.output_modules'). 
I would be so thankful if you help me to have the correct python script to train my model. 

Best regards,
Somayeh

##########################
import os
from schnetpack.data import AtomsDataModule
from schnetpack.model import AtomisticModel
from schnetpack.representation import SchNet
from schnetpack.output_modules import Atomwise
from schnetpack.train import Trainer
from schnetpack.evaluation import MeanAbsoluteError

db_path = "dataset.db"

if not os.path.exists(db_path):
    raise FileNotFoundError(f"Database not found at {db_path}")

# Set up data module
datamodule = AtomsDataModule(
    datapath=dp_path,
    batch_size=10,
    num_train=950,
    num_val=50,
    split_file="split.npz",
    load_properties=["energy", "forces"],
)
datamodule.prepare_data()
datamodule.setup()

################################################
#   Define the Model
################################################
representation = SchNet(
        n_atom_basis=128, # number of features per atom
        n_interactions=3, # number of iteration blocks 
        cutoff=8.5
)

output = Atomwise(
    property="energy",  # Target property
    derivative="forces",  # Forces as derivative of energy
    negative_dr=True     # Include forces with the correct sign
)

model = AtomisticModel(representation, output)

################################################
#   Set up training
################################################
# Set the trainer parameters
trainer = Trainer(
    model=model,
    datamodule=datamodule,
    max_epochs=100000,        # Number of epochs 
    gpus=1,                # Use GPUs, set to 0 for CPU 
    output_dir="results",  # Directory to save outputs
    lr=1e-4,               # learning rate
)

# Train the model
trainer.fit()

################################################
#  Evaluate the Model
################################################

results = trainer.test()
print("Test Results:", results)

# Define metrics
metrics = {"energy_mae": MeanAbsoluteError("energy"), "force_mae": MeanAbsoluteError("forces")}

# Evaluate
results = trainer.test(test_dataloaders=test_loader, metrics=metrics)
print(results)

**Comment by jnsLs** [comment]
Hi, 
it looks like you are, at least in parts, using a pretty old verson of schnetpack (<2.0.0) in your script. Is this consistent with the version you have installed? The errors suggest the contrary.
Best regards, 
Jonas

**Comment by SoFarN** [comment]
Hi, 
Thank you for your reply. 
No, I am using the latest version of SchNetPack. However, I am not much familiar to how prepare my own script to read data. Could you please help me to modify my script and resolve the issues? May I kindly ask you if you have a template script that I can play with that? 

Best regards,
Somayeh

**Comment by jnsLs** [comment]
We have several tutorials on how to prepare your own data, train models and run simulations in `examples/tutorials` 
Best regards, 
Jonas
