### ISSUE TITLE
Evaluation.py   _get_predicted(self, device) for clusters with different number of atoms

### ISSUE THREAD

**Issue by lmj1029123** [atomistic-machine-learning/schnetpack#69]
Hi,

I am trying to predict the forces of clusters using the best_model. However, it seems that if the clusters are of various size, the _get_predicted function would not work.  The problem is in 

```
for p in predicted.keys():
            predicted[p] = np.vstack(predicted[p])
```

```
ValueError: all the input array dimensions except for the concatenation axis must match exactly
```
Thanks!

**Comment by Stefaanhess** [comment]
Hey @lmj1029123,

the evaluation for datasets with different sized molecules and atomic properties should be ok now.
