### ISSUE TITLE
Scalability of SchNet

### ISSUE THREAD

**Issue by Dom1L** [atomistic-machine-learning/schnetpack#95]
Hi guys,

I was playing around with the package and wanted to know what the limits of SchNet are. So I tried to feed a protein (trypsin, 1700 atoms) into the network using the default settings and ran into some Cuda out of memory errors (TitanV 12GB).
I tried to scale the features, number of interactions blocks etc. down while using a batch size of 1 and still did not get it to work. 
So what is your experience with the scalability of this network? Do you think it is due to the model itself (including distance matrices, features, rbf etc.), the implementation (optimizing it a bit more) or did I approach it wrong?

In case you want to reproduce it, I made a small script and a  .db file including 100x trypsin with a dummy energy value.

Thanks for your help and this nice package.

```python
import torch
import torch.nn.functional as F
from torch.optim import Adam

import schnetpack as spk
from schnetpack.data import AtomsData
import schnetpack.atomistic as atm
import schnetpack.representation as rep

data = AtomsData('3ptb.db', properties=['energy'])

# split in train and val
train, val, test = data.create_splits(80, 20)
loader = spk.data.AtomsLoader(train, batch_size=1, num_workers=1)
val_loader = spk.data.AtomsLoader(val)

# create model
reps = rep.SchNet(
    n_atom_basis=32,
    n_filters=128,
    n_interactions=1,
    cutoff=5.0,
    n_gaussians=25,
    normalize_filter=False,
    coupled_interactions=True,
    return_intermediate=False,
    max_z=100,
    trainable_gaussians=False,
    distance_expansion=None)
output = atm.Atomwise()
model = atm.AtomisticModel(reps, output).cuda()

opt = Adam(model.parameters(), lr=1e-4)
loss = lambda b, p: F.mse_loss(p["y"], b['energy'])
trainer = spk.train.Trainer("output/", model, loss, opt, loader, val_loader)

trainer.train(torch.device("cuda"))
```
[3ptbdb.zip](https://github.com/atomistic-machine-learning/schnetpack/files/3044397/3ptbdb.zip)

**Comment by ktschuett** [comment]
Hi,
the default SimpleEnvironmentProvider assumes a dense interaction matrix, which will be huge since you have such a large molecule. You should try the AseEnvironmentProvider with an appropriate cutoff: 
`
cutoff = 5. # Angstrom
environment_provider = spk.environment.AseEnvironmentProvider(cutoff)
data = AtomsData('3ptb.db', properties=['energy'], environment_provider=environment_provider)
`
