### ISSUE TITLE
Share trained model

### ISSUE THREAD

**Issue by w6ye** [atomistic-machine-learning/schnetpack#98]
Hi,

I am really interested in the SchNet's performance in crystals. I wonder if you could share the best trained models, especailly the one trained with Materials Project data? 

Thanks!

Weike

**Comment by ktschuett** [comment]
We're currently looking to do this in the upcoming release for QM9. We will consider also doing one for MP.

**Comment by Stefaanhess** [comment]
Hi @w6ye ,

I just added the trained models and a benchmark table to the docs in #160 .
